#include "../src/runtime/jockstrap_worker.h"
#include <chrono>
#include <iostream>
#include <stdexcept>
namespace G=malemod::garments;
static G::Sample S(G::Point p,unsigned i){G::Sample s{p,{0,1,0},{}};s.lineage.donors[0]={G::Surface::Anatomy,i,1};return s;}
static std::shared_ptr<G::Input> Fixture(unsigned long long epoch){auto in=std::make_shared<G::Input>();in->characterEpoch=epoch;in->topologyRevision=1;in->gravity={0,0,-9.81};for(unsigned i=0;i<24;i++){double t=i*6.283185307179586/24;in->waist.push_back(S({.2*cos(t),.15*sin(t),1},i));in->opening.push_back(S({.05*cos(t),.12,.7+.05*sin(t)},i));}for(unsigned j=0;j<24;j++)for(unsigned i=0;i<48;i++){double p=3.141592653589793*(j+.1)/24,t=i*6.283185307179586/48;in->anatomy.push_back(S({.05*sin(p)*cos(t),.2+.15*sin(p)*sin(t),.65+.1*cos(p)},i+j*48));}for(unsigned side=0;side<2;side++){double s=side?1:-1;in->rearStraps[side]={S({s*.15,-.1,.99},0),S({s*.13,-.1,.7},1),S({s*.05,.12,.62},2)};}return in;}
static std::shared_ptr<const G::Output> Wait(JockstrapCpuWorker& worker,unsigned long long epoch){auto until=std::chrono::steady_clock::now()+std::chrono::seconds(3);while(std::chrono::steady_clock::now()<until){auto result=worker.Poll(epoch);if(result)return result;std::this_thread::sleep_for(std::chrono::milliseconds(1));}throw std::runtime_error("Garment worker timed out");}
int main(){try{JockstrapCpuWorker worker;auto input=Fixture(42);auto before=std::chrono::steady_clock::now();worker.Submit(input);double submit=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-before).count();auto first=Wait(worker,42);if(first->mesh.vertices.empty()||submit>5)throw std::runtime_error("Generation blocked submit");for(unsigned i=0;i<128;i++)worker.Submit(Fixture(43+i));auto final=Wait(worker,170);if(final->characterEpoch!=170||worker.Poll(42))throw std::runtime_error("Stale epoch published");auto retained=final;worker.Clear();if(worker.Poll(170)||retained->mesh.vertices.empty())throw std::runtime_error("Clear corrupted immutable snapshot");worker.Submit(Fixture(170));auto resumed=Wait(worker,170);if(resumed->mesh.vertices.size()!=retained->mesh.vertices.size())throw std::runtime_error("Topology changed across lifecycle");worker.Stop();std::cout<<"PASS CPU worker latest request, epoch rejection, immutable snapshots, clear/resume/stop; submit="<<submit<<"ms\n";return 0;}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
