// Exercise the production donor skin function with actual canonical native
// buffers/remap tables and distinguishable per-section/per-bone transforms.
// This does not create a graphics device or launch/install a game.
#include "../src/runtime/d3d9_proxy.cpp"
#include <iostream>
int main(){using namespace JockstrapAdapter;renderFrameSerial=73;tankCameraSceneTick=0;for(unsigned i=0;i<nrCount;i++)memcpy(nrPacked+i*32+12,nrAttributes+i*20,20);for(unsigned section=0;section<3;section++){paletteFrame[section]=73;paletteCount[section]=75;for(unsigned bone=0;bone<75;bone++){auto* matrix=palettes[section]+bone*12;memset(matrix,0,48);matrix[0]=matrix[5]=matrix[10]=1;matrix[3]=float(section*100+bone);matrix[7]=float(section*7);}}
 G::Vertex vertex;vertex.position={1,2,3};vertex.normal={0,0,1};vertex.uv={.25,.75};vertex.lineage.donors={G::Donor{G::Surface::Body,19558,.2},G::Donor{G::Surface::Body,42640,.3},G::Donor{G::Surface::Anatomy,5000,.5},G::Donor{}};RenderVertex result{};if(!Pose(vertex,result)){std::cerr<<"Production mixed native skin failed\n";return 1;}
 double expectedX=1,expectedY=2,total=0;for(auto donor:vertex.lineage.donors){if(donor.weight<=0)continue;unsigned section;const unsigned char* packed;const unsigned char* bones;if(donor.surface==G::Surface::Anatomy){section=2;packed=nrPacked+donor.vertex*32;bones=packed+20;}else{section=donor.vertex>=41435?1:0;unsigned local=donor.vertex-(section?41435:17449);packed=sharedBodyBase[section]+local*32;bones=(section?fluidGameplayBones1:fluidGameplayBones0)+local*4;}for(unsigned k=0;k<4;k++){double weight=donor.weight*packed[24+k]/255.;expectedX+=weight*(section*100+bones[k]);expectedY+=weight*section*7;total+=weight;}}
 // Native byte weights normalize after interpolation; the position term is
 // separately normalized, as the authoritative shader skin weights require.
 expectedX=(expectedX-1)/total+1;expectedY=(expectedY-2)/total+2;if(fabs(result.p[0]-expectedX)>2e-5||fabs(result.p[1]-expectedY)>2e-5||fabs(result.p[2]-3)>1e-6||fabs(result.n[2]-1)>1e-6){std::cerr<<"Wrong source donor section/skin blend\n";return 1;}
 paletteFrame[1]=72;if(Pose(vertex,result)){std::cerr<<"Accepted stale body palette\n";return 1;}paletteFrame[1]=73;paletteCount[1]=1;if(Pose(vertex,result)){std::cerr<<"Accepted missing native bone\n";return 1;}paletteCount[1]=75;
 // Preserve actual packed donor/remap tables while independently varying the
 // observed native actor transform and each section's articulated skin rows.
 std::vector<unsigned char> body((sharedBodyFirst[1]+sharedBodyCount[1])*32);for(unsigned section=0;section<2;section++)memcpy(body.data()+sharedBodyFirst[section]*32,sharedBodyBase[section],sharedBodyCount[section]*32);currentBody=body.data();
 for(unsigned section=0;section<3;section++){memset(sectionLocal[section],0,64);for(unsigned i=0;i<4;i++)sectionLocal[section][i*5]=1;sectionLocal[section][0]=0;sectionLocal[section][1]=1;sectionLocal[section][4]=-1;sectionLocal[section][5]=0;sectionLocal[section][12]=10;sectionLocal[section][13]=-20;sectionLocal[section][14]=30;}
 fluidWorldCameraFrame=73;fluidCameraWorld={};auto original=CapturePose(73);if(!original){std::cerr<<"Native pose capture rejected valid sections\n";return 1;}
 auto independent=[&](const G::Lineage& lineage){G::Point out{};double total=0;for(auto donor:lineage.donors)if(donor.weight>0){const unsigned char* packed=donor.surface==G::Surface::Body?currentBody+donor.vertex*32:nrPacked+donor.vertex*32;G::Point bind=Position(packed);unsigned section=2;const unsigned char* weights=packed+24;const unsigned char* bones=packed+20;if(donor.surface==G::Surface::Body){int si;UINT local;MenuRetargetBodyVertex(donor.vertex,si,local);section=unsigned(si);bones=(si?fluidGameplayBones1:fluidGameplayBones0)+local*4;}double sum=0;for(unsigned k=0;k<4;k++)sum+=weights[k];for(unsigned k=0;k<4;k++)if(weights[k]){double w=donor.weight*weights[k]/sum;auto* m=palettes[section]+bones[k]*12;double x=m[0]*bind[0]+m[1]*bind[1]+m[2]*bind[2]+m[3],y=m[4]*bind[0]+m[5]*bind[1]+m[6]*bind[2]+m[7],z=m[8]*bind[0]+m[9]*bind[1]+m[10]*bind[2]+m[11];out=G::Add(out,G::Mul({10-y,-20+x,30+z},w));total+=w;}}return G::Mul(out,1/total);};
 G::Sample sample;sample.lineage=vertex.lineage;WorldSample(sample,*original);auto expected=independent(vertex.lineage);if(G::Length(G::Sub(sample.position,expected))>1e-8){std::cerr<<"Mixed donor sample skins interpolation incorrectly\n";return 1;}
 G::Input bodyContact;CompleteBodySurface(bodyContact);if(bodyContact.bodySurface.size()!=sharedBodyCount[0]+sharedBodyCount[1]||bodyContact.bodyTriangles.size()!=menuRetargetBodyTriangleCount0+menuRetargetBodyTriangleCount1){std::cerr<<"Actual body collision resources incomplete\n";return 1;}for(auto face:bodyContact.bodyTriangles){for(auto id:face)if(id>=bodyContact.bodySurface.size()){std::cerr<<"Actual body collision face outside measured vertices\n";return 1;}const auto& a=bodyContact.bodySurface[face[0]];const auto& b=bodyContact.bodySurface[face[1]];const auto& c=bodyContact.bodySurface[face[2]];auto cross=G::Cross(G::Sub(b.position,a.position),G::Sub(c.position,a.position));if(!G::Finite(cross)){std::cerr<<"Canonical measured body contact face is nonfinite\n";return 1;}}for(unsigned section=0,first=0;section<2;first+=sharedBodyCount[section++])for(unsigned local:{0u,sharedBodyCount[section]-1}){auto measured=bodyContact.bodySurface[first+local];WorldSample(measured,*original);if(measured.lineage.donors[0].vertex!=sharedBodyFirst[section]+local||G::Length(G::Sub(measured.position,independent(measured.lineage)))>1e-8){std::cerr<<"Body collision surface uses different native pose or lineage\n";return 1;}}
 // The native resources have globally consistent edges, while four stock
 // normal outliers would invert isolated faces if voted independently.
 const unsigned short* stockFaces[]={menuRetargetBodyIndices0,menuRetargetBodyIndices1};const unsigned faceCounts[]={menuRetargetBodyTriangleCount0,menuRetargetBodyTriangleCount1};unsigned mismatchedNormals=0;for(unsigned section=0,first=0,at=0;section<2;first+=sharedBodyCount[section++])for(unsigned face=0;face<faceCounts[section];face++,at++){auto actual=bodyContact.bodyTriangles[at];if(actual!=std::array<std::uint32_t,3>{first+stockFaces[section][face*3],first+stockFaces[section][face*3+2],first+stockFaces[section][face*3+1]}){std::cerr<<"Body contact-only orientation changed native edge connectivity\n";return 1;}auto a=bodyContact.bodySurface[actual[0]],b=bodyContact.bodySurface[actual[1]],c=bodyContact.bodySurface[actual[2]];auto normal=G::Add(a.normal,G::Add(b.normal,c.normal)),cross=G::Cross(G::Sub(b.position,a.position),G::Sub(c.position,a.position));mismatchedNormals+=G::Length(cross)>1e-12&&G::Dot(cross,normal)<0;}if(mismatchedNormals!=4){std::cerr<<"Measured stock normal outlier provenance changed\n";return 1;}
 // Deferred production conversion must agree with the old direct donor path
 // after the game-owned buffers have changed. Retain no mutable game pointers.
 auto geometry=CaptureGeometry(*original);G::Input deferred;auto conversionBegan=std::chrono::steady_clock::now();PrepareSnapshotInput(deferred,*original,*geometry);std::cout<<"Deferred complete native cloth sampling "<<std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-conversionBegan).count()<<"ms\n";for(unsigned t=0;t<nrIndexCount/3;t++)if(deferred.anatomyTriangles[t]!=std::array<std::uint32_t,3>{nrIndices[t*3],nrIndices[t*3+2],nrIndices[t*3+1]}){std::cerr<<"Contact-only anatomy winding differs from observed opposite-to-render normals\n";return 1;}
 for(auto* contour:{&deferred.waist,&deferred.opening,&deferred.anatomy,&deferred.rearStraps[0],&deferred.rearStraps[1],&deferred.bodySurface})for(auto& row:*contour)if(G::Length(G::Sub(row.position,independent(row.lineage)))>1e-8){std::cerr<<"Deferred completed geometry differs from original donor oracle\n";return 1;}
 auto liveAnatomy=std::vector<unsigned char>(nrPacked,nrPacked+sizeof(nrPacked));std::fill(body.begin(),body.end(),0);memset(nrPacked,0,sizeof(nrPacked));G::Input afterMutation;conversionBegan=std::chrono::steady_clock::now();PreparationTiming breakdown;PrepareSnapshotInput(afterMutation,*original,*geometry,&breakdown);std::cout<<"Sampling phases: lineage/topology="<<breakdown.lineageMilliseconds<<"ms world="<<breakdown.worldMilliseconds<<"ms uniqueMatrices="<<breakdown.uniqueMatrices<<"\n";std::cout<<"Deferred cached-topology sampling "<<std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-conversionBegan).count()<<"ms\n";for(unsigned k=0;k<2;k++)memcpy(body.data()+sharedBodyFirst[k]*32,geometry->body[k].data(),geometry->body[k].size());memcpy(nrPacked,liveAnatomy.data(),liveAnatomy.size());
 const std::vector<G::Sample>* oldRows[]={&deferred.waist,&deferred.opening,&deferred.anatomy,&deferred.rearStraps[0],&deferred.rearStraps[1],&deferred.bodySurface};const std::vector<G::Sample>* newRows[]={&afterMutation.waist,&afterMutation.opening,&afterMutation.anatomy,&afterMutation.rearStraps[0],&afterMutation.rearStraps[1],&afterMutation.bodySurface};for(unsigned k=0;k<6;k++)for(unsigned j=0;j<oldRows[k]->size();j++)if((*oldRows[k])[j].position!=(*newRows[k])[j].position||(*oldRows[k])[j].normal!=(*newRows[k])[j].normal){std::cerr<<"Deferred cloth conversion read a mutated game buffer\n";return 1;}
 if(deferred.anatomy.size()!=17528||deferred.anatomyTriangles.size()!=35000||deferred.anatomyRegions!=afterMutation.anatomyRegions||deferred.anatomyRegions[0].size()!=5448||deferred.anatomyRegions[1].size()!=2993||deferred.anatomyRegions[2].size()!=3851||deferred.anatomyRegions[3].size()!=3771){std::cerr<<"Measured anatomical guide semantics changed or replaced full mesh\n";return 1;} if(deferred.bodyTriangles!=afterMutation.bodyTriangles||deferred.anatomyTriangles!=afterMutation.anatomyTriangles){std::cerr<<"Deferred topology changed with game writes\n";return 1;}
 // Recompose actual native tuple rows under changing affine poses; compare
 // every position and normal with the original uncached packed-donor function.
 auto articulated=*original;for(unsigned section=0;section<3;section++)for(unsigned bone=0;bone<75;bone++){auto& m=articulated.world[section][bone];m[0]*=1+.003*bone;m[5]*=1-.001*bone;m[1]+=.001*(bone%7);m[7]+=.07*bone;m[11]-=.03*bone;}G::Input changedPose;PrepareSnapshotInput(changedPose,articulated,*geometry);for(auto* contour:{&changedPose.waist,&changedPose.opening,&changedPose.anatomy,&changedPose.rearStraps[0],&changedPose.rearStraps[1],&changedPose.bodySurface})for(auto& row:*contour){auto oracle=row;WorldSample(oracle,articulated,geometry.get());if(row.position!=oracle.position||row.normal!=oracle.normal){std::cerr<<"Dense cached sampling changed original donor arithmetic or froze pose\n";return 1;}}
 auto changedGeometry=*geometry;changedGeometry.anatomy[5000*32+20]=73;changedGeometry.anatomy[5000*32+24]=255;for(unsigned k=1;k<4;k++)changedGeometry.anatomy[5000*32+24+k]=0;G::Input rebound;PrepareSnapshotInput(rebound,articulated,changedGeometry);auto changedOracle=rebound.anatomy[5000];WorldSample(changedOracle,articulated,&changedGeometry);if(rebound.anatomy[5000].position!=changedOracle.position||rebound.anatomy[5000].normal!=changedOracle.normal||rebound.anatomy[5000].position==changedPose.anatomy[5000].position){std::cerr<<"Dense tuple slot failed to rebind changed native skin bytes\n";return 1;}
 PreparationTiming retainedCapacity;conversionBegan=std::chrono::steady_clock::now();PrepareSnapshotInput(afterMutation,*original,*geometry,&retainedCapacity);std::cout<<"Sampling retained worker capacities "<<std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-conversionBegan).count()<<"ms lineage="<<retainedCapacity.lineageMilliseconds<<"ms world="<<retainedCapacity.worldMilliseconds<<"ms\n";
 // Route geometry uses actual native lateral waist and same-side body guides.
 for(unsigned side=0;side<2;side++){std::vector<G::Sample> route;if(side)Contour(jockstrap_strapRight,route,G::Surface::Body);else Contour(jockstrap_strapLeft,route,G::Surface::Body);const double sign=side?1:-1;double lowest=route[0].position[2];if(route.size()<16||std::abs(route[0].position[0])>1||route[0].position[1]*sign<12||std::abs(route.back().position[1])>2){std::cerr<<"Measured strap does not begin at lateral hip or return medially\n";return 1;}for(const auto& row:route){lowest=(std::min)(lowest,row.position[2]);if(row.position[1]*sign<-.01){std::cerr<<"Measured strap crosses opposite glute\n";return 1;}}if(lowest>80){std::cerr<<"Measured strap never passes under the glute fold\n";return 1;}}
 // The shared sheet can retain sixteen support donors; native bone tuples
 // remain four influences per donor. Exercise every support slot, including
 // the tail, against individually evaluated native donor maps.
 static_assert(std::tuple_size<decltype(G::Lineage{}.donors)>::value==16,"Expanded garment lineage contract differs");
 G::Sample extended;for(unsigned i=0;i<16;i++)extended.lineage.donors[i]={i%3?G::Surface::Anatomy:G::Surface::Body,i%3?5000+i:19558+i,double(i+1)/136.};
 WorldSample(extended,*original,geometry.get());if(G::Length(G::Sub(extended.position,independent(extended.lineage)))>1e-8){std::cerr<<"Expanded garment donor interpolation truncates support slots\n";return 1;}
 SamplingMaps extendedCache;extendedCache.Begin();auto cachedExtended=extended;WorldSample(cachedExtended,articulated,geometry.get(),&extendedCache);auto directExtended=extended;WorldSample(directExtended,articulated,geometry.get());if(cachedExtended.position!=directExtended.position||cachedExtended.normal!=directExtended.normal){std::cerr<<"Expanded cached donor interpolation differs\n";return 1;}
 auto mixedMap=NativeMap(extended.lineage,articulated,true,geometry.get());K::Matrix separateMap{};for(const auto& donor:extended.lineage.donors){G::Lineage single;single.donors[0]={donor.surface,donor.vertex,1};auto one=NativeMap(single,articulated,true,geometry.get());for(unsigned j=0;j<12;j++)separateMap[j]+=one[j]*donor.weight;}for(unsigned j=0;j<12;j++)if(std::abs(mixedMap[j]-separateMap[j])>1e-10){std::cerr<<"Expanded native transport map drops donor contributions\n";return 1;}
 vertex.lineage=extended.lineage;
 auto sourceMap=NativeMap(vertex.lineage,*original,true);G::Point bindPoint{1,2,3};vertex.position=K::Point(sourceMap,bindPoint);vertex.normal=K::Normal(sourceMap,{0,0,1});
 auto record=std::make_shared<JockstrapCpuWorker::Delivery>();record->pose=original;solved=record;
 renderFrameSerial=74;for(unsigned section=0;section<3;section++){paletteFrame[section]=74;sectionLocal[section][12]+=5;sectionLocal[section][13]-=2;for(unsigned bone=0;bone<75;bone++)palettes[section][bone*12+11]+=float(section)*.25f;}
 fluidWorldCameraFrame=74;displayPose=CapturePose(74);if(!displayPose||!Pose(vertex,result)){std::cerr<<"Solved world cloth failed current native pose transport\n";return 1;}
 auto actual=K::Point(displayPose->actor[2],{result.p[0],result.p[1],result.p[2]});expected=K::Point(NativeMap(vertex.lineage,*displayPose,true),bindPoint);if(G::Length(G::Sub(actual,expected))>2e-5){std::cerr<<"Solved cloth actor transform doubled or current articulation lost\n";return 1;}
 auto normal=K::Normal(displayPose->actor[2],{result.n[0],result.n[1],result.n[2]});auto expectedNormal=K::Normal(NativeMap(vertex.lineage,*displayPose,true),{0,0,1});if(G::Length(G::Sub(normal,expectedNormal))>1e-6){std::cerr<<"World/native cloth lighting frame differs\n";return 1;}
 auto stationary=displayPose;
 // Same actual actor, different camera/pre-view shift: world physics inputs
 // and output presentation must be invariant to camera movement.
 renderFrameSerial=75;fluidWorldCameraFrame=75;fluidCameraWorld={100,-50,25};for(unsigned section=0;section<3;section++){paletteFrame[section]=75;sectionLocal[section][12]-=100;sectionLocal[section][13]+=50;sectionLocal[section][14]-=25;}
 displayPose=CapturePose(75);if(!displayPose){std::cerr<<"Absolute native origin unavailable\n";return 1;}for(unsigned section=0;section<3;section++)for(unsigned j=0;j<12;j++)if(std::abs(displayPose->actor[section][j]-stationary->actor[section][j])>1e-9){std::cerr<<"Camera pre-view shift leaked into persistent actor pose\n";return 1;}
 if(!Pose(vertex,result)){std::cerr<<"Camera-independent cloth transport rejected\n";return 1;}auto sameWorld=K::Point(displayPose->actor[2],{result.p[0],result.p[1],result.p[2]});if(G::Length(G::Sub(sameWorld,actual))>2e-5){std::cerr<<"Camera movement changes cloth world form\n";return 1;}
 fluidWorldCameraFrame=74;if(CapturePose(75)){std::cerr<<"Accepted stale absolute world origin\n";return 1;}fluidWorldCameraFrame=75;
 paletteFrame[0]=73;if(CapturePose(75)){std::cerr<<"Accepted mixed-frame native world sample\n";return 1;}
 solved.reset();displayPose.reset();std::cout<<"PASS production actual packed/remapped mixed skin, independently skinned donor interpolation, actor translation/rotation, articulated world/native cloth transport, inverse-transpose lighting and stale frame/bone guards\n";return 0;}
