// Actual completed Base source surface through canonical native packed buffers.
// Offline authoring pose only: no graphics device, game, install or input.
#include "../src/runtime/d3d9_proxy.cpp"
#include <filesystem>
#include <fstream>
#include <iostream>
#include "garment_hem_checks.hpp"
namespace G=malemod::garments;
template<class T>static std::vector<T> Read(const std::filesystem::path& path,unsigned count){std::ifstream f(path,std::ios::binary);std::vector<T> out(count);f.read(reinterpret_cast<char*>(out.data()),sizeof(T)*count);if(!f||f.peek()!=EOF)throw std::runtime_error("Exact evaluated native resource byte count differs");return out;}
static void Check(bool condition,const char* message){if(!condition)throw std::runtime_error(message);}
static malemod::surface::Controls EvaluatedControls(const char* path){
 malemod::surface::Controls out;std::ifstream prefs(path);const unsigned order[18]={0,1,2,3,5,7,8,9,4,6,10,11,12,13,14,15,16,17};
 for(unsigned id:order){Check(bool(prefs>>out.values[id]),"Exact18 evaluated source preferences missing");Check(std::isfinite(out.values[id])&&out.values[id]>=0&&out.values[id]<=(id==0?2.f:100.f),"Evaluated preference outside UI contract");}
 std::string extra;Check(!(prefs>>extra),"Evaluated preferences contain trailing tokens");Check(std::floor(out.values[0])==out.values[0],"Mechanical state must be an exact UI integer");return out;
}
static void InputControls(const std::filesystem::path& report,const G::Input& input,const malemod::surface::Controls& controls,bool known){
 std::ofstream f(report/"source-input-controls.json");f.precision(17);f<<"{\"schema\":1,\"controlsKnown\":"<<(known?"true":"false")<<",\"oracleTokenAngleIndex\":5,\"runtimeControlAngleIndex\":7,\"mechanicalState\":"<<controls.values[0]<<",\"overall\":"<<controls.values[1]<<",\"restAngle\":"<<controls.values[7]<<",\"anatomyMass\":"<<input.anatomyMass<<",\"controls\":[";for(unsigned i=0;i<18;i++){if(i)f<<',';f<<controls.values[i];}f<<"],\"identityAuthoringPose\":true,\"observedGameplay\":false}\n";Check(bool(f),"Source UI metadata write failed");
}
static void JoinedCut(const std::filesystem::path& report,const G::Input& input){
 double circumference=0,height=0;for(unsigned i=0;i<input.waist.size();i++){circumference+=G::Length(G::Sub(input.waist[i].position,input.waist[(i+1)%input.waist.size()].position));height+=input.frame.Local(input.waist[i].position)[2];}height/=input.waist.size();G::Parameters parameters;const double width=parameters.bandWidth*circumference,bottom=height-width*.5,top=height+width*.5;
 std::string bodyFailure;try{G::waist::Intersect(input.bodySurface,input.bodyTriangles,input.frame,bottom,top,unsigned(input.waist.size()));}catch(const std::exception& error){bodyFailure=error.what();}
 const auto bodyFaces=input.bodyTriangles,anatomyFaces=input.anatomyTriangles;auto joined=G::waist::JoinedPhysicalSurface(input,circumference);Check(joined.samples.size()==input.bodySurface.size()+input.anatomy.size(),"Joined cut invented physical vertices");Check(joined.triangles.size()==joined.refinedBodyTriangles+input.anatomyTriangles.size(),"Joined cut appended classification caps");
 auto contours=G::waist::Intersect(joined.samples,joined.triangles,input.frame,bottom,top,unsigned(input.waist.size()));std::map<std::pair<unsigned,unsigned>,G::Point> nativePositions;for(const auto* rows:{&input.bodySurface,&input.anatomy})for(const auto& sample:*rows){const auto& donor=sample.lineage.donors[0];Check(donor.weight==1,"Complete native physical sample is not an exact single donor");nativePositions[{unsigned(donor.surface),donor.vertex}]=sample.position;}double maximumError=0,maximumNativeError=0,maximumHeightError=0;unsigned anatomyAttachments=0,bodyAttachments=0;
 std::ofstream json(report/"joined-cut-proof.json");json.precision(17);json<<"{\"scope\":\"Actual complete physical body and anatomy transverse cuts; no cloth walk\",\"bodyOnlyFailure\":\""<<bodyFailure<<"\",\"sourceAnatomyVertices\":"<<input.anatomy.size()<<",\"sourceAnatomyTriangles\":"<<input.anatomyTriangles.size()<<",\"sourceBodyVertices\":"<<input.bodySurface.size()<<",\"sourceBodyTriangles\":"<<input.bodyTriangles.size()<<",\"joinedVertices\":"<<joined.samples.size()<<",\"refinedBodyTriangles\":"<<joined.refinedBodyTriangles<<",\"joinedTriangles\":"<<joined.triangles.size()<<",\"classificationCapTrianglesAppended\":0,\"sourceCircumference\":"<<circumference<<",\"bottomHeight\":"<<bottom<<",\"topHeight\":"<<top<<",\"contours\":[";
 unsigned contourId=0;for(const auto* contour:{&contours.bottom,&contours.top}){if(contourId++)json<<',';json<<"{\"height\":"<<contour->height<<",\"circumference\":"<<contour->circumference<<",\"signedArea\":"<<contour->signedArea<<",\"points\":[";unsigned pointId=0;for(const auto& attachment:contour->points){G::Point reconstructed{},nativeReconstructed{};if(pointId++)json<<',';json<<"{\"position\":["<<attachment.position[0]<<','<<attachment.position[1]<<','<<attachment.position[2]<<"],\"vertices\":[";for(unsigned k=0;k<4;k++){if(k)json<<',';json<<attachment.vertices[k];}json<<"],\"weights\":[";for(unsigned k=0;k<4;k++){if(k)json<<',';json<<attachment.weights[k];if(attachment.weights[k]){const auto& sample=joined.samples.at(attachment.vertices[k]);reconstructed=G::Add(reconstructed,G::Mul(sample.position,attachment.weights[k]));for(const auto& d:sample.lineage.donors)if(d.weight){Check(d.vertex<(d.surface==G::Surface::Anatomy?nrCount:sharedBodyFirst[1]+sharedBodyCount[1]),"Joined cut native donor outside complete source buffers");nativeReconstructed=G::Add(nativeReconstructed,G::Mul(nativePositions.at({unsigned(d.surface),d.vertex}),d.weight*attachment.weights[k]));if(d.surface==G::Surface::Anatomy)anatomyAttachments++;else bodyAttachments++;}}}json<<"]}";maximumError=(std::max)(maximumError,G::Length(G::Sub(reconstructed,attachment.position)));maximumNativeError=(std::max)(maximumNativeError,G::Length(G::Sub(nativeReconstructed,attachment.position)));maximumHeightError=(std::max)(maximumHeightError,std::abs(input.frame.Local(attachment.position)[2]-contour->height));}json<<"]}";}
 json<<"],\"maximumNativeReconstructionError\":"<<maximumNativeError<<",\"maximumSurfaceReconstructionError\":"<<maximumError<<",\"maximumHeightError\":"<<maximumHeightError<<",\"bodyDonorContributions\":"<<bodyAttachments<<",\"anatomyDonorContributions\":"<<anatomyAttachments<<",\"physicalInputsChanged\":false,\"observedGameplay\":false}\n";json.close();Check(maximumError<circumference*1e-12&&maximumNativeError<circumference*1e-12&&maximumHeightError<circumference*1e-12,"Actual joined cut lost native donor or transverse plane accuracy");Check(input.bodyTriangles==bodyFaces&&input.anatomyTriangles==anatomyFaces,"Joined cut modified native physical topology");
 G::Output bandOutput;bandOutput.measuredCircumference=circumference;const auto band=G::detail::BuildBand(input,parameters,bandOutput);Check(band.measured.size()==7&&bandOutput.band.topAttachments==input.waist.size()&&bandOutput.band.bottomAttachments==input.waist.size(),"Production measured band did not retain all seven actual contours");
 double bandNativeError=0;unsigned mixedBandAttachments=0;
 for(const auto& row:band.measured)for(const auto& sample:row){
  G::Point native{};double sum=0;bool hasBody=false,hasAnatomy=false;
  for(const auto& donor:sample.lineage.donors)if(donor.weight){native=G::Add(native,G::Mul(nativePositions.at({unsigned(donor.surface),donor.vertex}),donor.weight));sum+=donor.weight;hasBody|=donor.surface==G::Surface::Body;hasAnatomy|=donor.surface==G::Surface::Anatomy;}
  Check(std::abs(sum-1)<1e-12,"Production band native lineage weights lost normalization");
  bandNativeError=(std::max)(bandNativeError,G::Length(G::Sub(native,sample.position)));mixedBandAttachments+=hasBody&&hasAnatomy;
 }
 Check(bandNativeError<circumference*1e-12,"Production band native lineage reconstruction differs");
 std::ofstream bandProof(report/"production-band-proof.json");bandProof.precision(17);bandProof<<"{\"actualContours\":7,\"samplesPerContour\":"<<input.waist.size()<<",\"maximumNativeReconstructionError\":"<<bandNativeError<<",\"mixedBodyAnatomyAttachments\":"<<mixedBandAttachments<<",\"topAttachments\":"<<bandOutput.band.topAttachments<<",\"bottomAttachments\":"<<bandOutput.band.bottomAttachments<<",\"classificationCapTrianglesAppended\":0,\"observedGameplay\":false}\n";
 std::cout<<"PASS actual joined physical cut: "<<joined.samples.size()<<" vertices/"<<joined.triangles.size()<<" faces, bottom C="<<contours.bottom.circumference<<" area="<<contours.bottom.signedArea<<", top C="<<contours.top.circumference<<" area="<<contours.top.signedArea<<", mixed donor contributions="<<bodyAttachments<<'/'<<anatomyAttachments<<", reconstruction="<<maximumError<<"; all seven production BuildBand cuts pass\n";
}
#include "garment_input_json.hpp"
int main(int argc,char** argv){try{
 if(argc!=3&&argc!=4&&argc!=5)throw std::runtime_error("usage: garment_source_sheet_test evaluatedSourcePrefix ownedReportDirectory [option] [exact18PreferencesFile]");
 using namespace JockstrapAdapter;std::filesystem::path prefix(argv[1]),report(argv[2]);std::filesystem::create_directories(report);
 const bool controlsKnown=argc==5;auto evaluatedControls=controlsKnown?EvaluatedControls(argv[4]):malemod::surface::Controls{};
 auto xyz=Read<std::array<float,3>>(prefix,nrCount),normals=Read<std::array<float,3>>(prefix.string()+".normals",nrCount);auto triangles=Read<unsigned short>(prefix.string()+".indices",nrIndexCount);
 Check(std::equal(triangles.begin(),triangles.end(),nrIndices),"Evaluated complete anatomy index order changed");
 std::vector<unsigned char> body((sharedBodyFirst[1]+sharedBodyCount[1])*32);for(unsigned section=0;section<2;section++){auto positions=Read<std::array<float,3>>(prefix.string()+".body"+std::to_string(section),sharedBodyCount[section]);for(unsigned i=0;i<sharedBodyCount[section];i++){auto* out=body.data()+(sharedBodyFirst[section]+i)*32;memcpy(out,sharedBodyBase[section]+i*32,32);memcpy(out,positions[i].data(),12);}}
 for(unsigned i=0;i<nrCount;i++){auto* packed=nrPacked+i*32;memcpy(packed,xyz[i].data(),12);memcpy(packed+12,nrAttributes+i*20,20);for(unsigned a=0;a<3;a++)packed[16+a]=static_cast<unsigned char>(std::clamp(std::lround((double(normals[i][a])+1)*127.5),0l,255l));}
 currentBody=body.data();K::Pose pose;pose.serial=1;for(unsigned section=0;section<3;section++){pose.count[section]=75;pose.actor[section]=pose.inverseActor[section]=K::Identity();for(unsigned bone=0;bone<75;bone++)pose.skin[section][bone]=pose.world[section][bone]=K::Identity();}
 auto geometry=CaptureGeometry(pose);G::Input input;input.characterEpoch=1;input.topologyRevision=1;input.restRevision=1;input.frame.lateral={0,-1,0};input.frame.forward={1,0,0};input.frame.up={0,0,1};input.gravity={0,0,-72};input.anatomyMass=G::CurrentSourceMasses(evaluatedControls).Total();PreparationTiming sampling;auto started=std::chrono::steady_clock::now();PrepareSnapshotInput(input,pose,*geometry,&sampling);double inputMs=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-started).count();
 Check(input.anatomy.size()==17528&&input.anatomyTriangles.size()==35000&&input.bodySurface.size()==20783,"Canonical sheet replaced complete native tissue/body");
 if(argc>=4&&std::string(argv[3])=="--joined-cut-only"){JoinedCut(report,input);return 0;}
 if(argc>=4&&(std::string(argv[3])=="--input-json"||std::string(argv[3])=="--input-only")){WriteCanonicalGarmentInput(report/"native-input.json",input);InputControls(report,input,evaluatedControls,controlsKnown);if(std::string(argv[3])=="--input-only")return 0;}
 double measuredC=0;for(unsigned i=0;i<input.waist.size();i++)measuredC+=G::Length(G::Sub(input.waist[i].position,input.waist[(i+1)%input.waist.size()].position));auto cap=G::RootCap(input.anatomy,input.anatomyTriangles,input.opening,measuredC);Check(input.opening.size()==54&&cap.size()==52,"Canonical complete measured54 root boundary does not cap exactly");auto closed=input.anatomyTriangles;closed.insert(closed.end(),cap.begin(),cap.end());Check(G::closure_detail::Extract(input.anatomy,closed,measuredC).loops.empty(),"Canonical classification closure retains unmatched edges");std::cout<<"PASS classification-only54 root boundary/52 cap faces; full physical anatomy unchanged17528/35000\n";std::ofstream closure(report/"closure-proof.json");closure<<"{\"fullAnatomyVertices\":17528,\"fullAnatomyTriangles\":35000,\"bodyVertices\":20783,\"openingVertices\":54,\"classificationCapFaces\":52,\"unmatchedEdges\":0,\"measuredCircumference\":"<<measuredC<<",\"physicalTrianglesChanged\":false,\"observedGameplay\":false}\n";closure.close();auto bodyCap=G::SurfaceCaps(input.bodySurface,input.bodyTriangles,measuredC);auto closedBody=input.bodyTriangles;closedBody.insert(closedBody.end(),bodyCap.begin(),bodyCap.end());Check(G::closure_detail::Extract(input.bodySurface,closedBody,measuredC).loops.empty(),"Canonical measured body classification closure retains unmatched edges");std::cout<<"PASS resource-coherent complete body classification closure, cap faces="<<bodyCap.size()<<"; native draw/normal bytes unchanged\n";std::ofstream bodyClosure(report/"body-closure-proof.json");bodyClosure<<"{\"bodyVertices\":20783,\"bodyFaces\":"<<input.bodyTriangles.size()<<",\"classificationCapFaces\":"<<bodyCap.size()<<",\"unmatchedEdges\":0,\"physicalTrianglesChanged\":false,\"nativeNormalOutliersPreserved\":4,\"observedGameplay\":false}\n";bodyClosure.close();if(argc>=4){Check(std::string(argv[3])=="--closure-only"||std::string(argv[3])=="--input-json","Unknown source-sheet test option");if(std::string(argv[3])=="--closure-only")return 0;}G::Parameters parameters;parameters.simulate=false;G::Session session(parameters);started=std::chrono::steady_clock::now();const auto& output=session.Update(G::Style::WhiteJockstrap,input);double fitMs=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-started).count();
 const auto hem=G::hem_checks::Check(output,parameters,false);const bool smoothHem=hem.maximumTurnRadians<=3.14159265358979323846/3;const auto& layout=output.layout;Check(layout.revision==2&&std::abs(layout.upperArcRadians-80*3.14159265358979323846/180)<1e-12,"Single-sheet layout or exact80 degree total upper seam differs");
 Check(layout.topSeam.size()==layout.sheet.columns+1&&layout.sheetFaces.count==2*layout.sheet.rows*layout.sheet.columns,"Connected rectangular sheet topology differs");
 Check(output.mesh.vertices.size()<65536&&layout.sheetFaces.start+layout.sheetFaces.count<=output.mesh.triangles.size(),"Typed sheet exceeds canonical native index capacity");
 for(unsigned row=0;row<layout.sheet.rows;row++)for(unsigned col=0;col<layout.sheet.columns;col++){unsigned id=layout.sheet.start+row*(layout.sheet.columns+1)+col;auto first=output.mesh.triangles[layout.sheetFaces.start+2*(row*layout.sheet.columns+col)].vertices,second=output.mesh.triangles[layout.sheetFaces.start+2*(row*layout.sheet.columns+col)+1].vertices;Check(first==std::array<std::uint32_t,3>{id,id+1,id+layout.sheet.columns+2}&&second==std::array<std::uint32_t,3>{id,id+layout.sheet.columns+2,id+layout.sheet.columns+1},"Typed sheet no longer forms the one rectangular material web");}
 for(unsigned col=0;col<layout.topSeam.size();col++)Check(layout.topSeam[col]==layout.sheet.start+col,"Broad upper seam differs from top sheet edge");
 for(auto ribbon:layout.straps)Check(ribbon.corners==4&&ribbon.sections>=2&&ribbon.start+ribbon.sections*ribbon.corners<=output.mesh.vertices.size(),"Typed strap range exceeds native garment mesh");
 Check(layout.band.start+layout.bandLayers*(layout.band.rows+1)*(layout.band.columns+1)<=output.mesh.vertices.size(),"Typed measured band outside native garment mesh");
 Check(!layout.bottomSeams[0].empty()&&!layout.bottomSeams[1].empty()&&layout.bottomSeams[0].size()<layout.topSeam.size()&&layout.bottomSeams[1].size()<layout.topSeam.size(),"Two smaller sewn lower sheet seams differ");
 std::array<unsigned,4> material{};double minimumArea=1e100,minimumUvArea=1e100,maximumEdge=0;unsigned flat=0;
 for(const auto& v:output.mesh.vertices){Check(G::Finite(v.position)&&G::Finite(v.normal)&&G::Finite(v.tangent)&&std::isfinite(v.uv[0])&&std::isfinite(v.uv[1]),"Nonfinite native sheet output");double sum=0;for(auto donor:v.lineage.donors)if(donor.weight){Check(std::isfinite(donor.weight)&&donor.weight>=0,"Invalid material support weight");Check(donor.vertex<(donor.surface==G::Surface::Anatomy?nrCount:sharedBodyFirst[1]+sharedBodyCount[1]),"Material support index outside complete native buffers");sum+=donor.weight;}Check(std::abs(sum-1)<1e-8,"Full material support sum differs");}
 for(const auto& face:output.mesh.triangles){Check(unsigned(face.material)<4,"Native material slot differs");material[unsigned(face.material)]++;for(auto index:face.vertices)Check(index<output.mesh.vertices.size(),"Native sheet face index out of bounds");const auto& a=output.mesh.vertices[face.vertices[0]],b=output.mesh.vertices[face.vertices[1]],c=output.mesh.vertices[face.vertices[2]];double area=G::Length(G::Cross(G::Sub(b.position,a.position),G::Sub(c.position,a.position)))*.5;minimumArea=(std::min)(minimumArea,area);flat+=area<1e-14;double uvArea=std::abs((b.uv[0]-a.uv[0])*(c.uv[1]-a.uv[1])-(b.uv[1]-a.uv[1])*(c.uv[0]-a.uv[0]))*.5;minimumUvArea=(std::min)(minimumUvArea,uvArea);for(unsigned k=0;k<3;k++)maximumEdge=(std::max)(maximumEdge,G::Length(G::Sub(output.mesh.vertices[face.vertices[k]].position,output.mesh.vertices[face.vertices[(k+1)%3]].position)));}
 for(auto n:material)Check(n>0,"Missing native cloth material slice");
 std::ofstream obj(report/"garment.obj");obj.precision(12);for(auto v:output.mesh.vertices)obj<<"v "<<v.position[0]<<' '<<v.position[1]<<' '<<v.position[2]<<'\n';for(auto v:output.mesh.vertices)obj<<"vt "<<v.uv[0]<<' '<<v.uv[1]<<'\n';for(auto f:output.mesh.triangles)obj<<"f "<<f.vertices[0]+1<<'/'<<f.vertices[0]+1<<' '<<f.vertices[1]+1<<'/'<<f.vertices[1]+1<<' '<<f.vertices[2]+1<<'/'<<f.vertices[2]+1<<'\n';
 std::ofstream json(report/"sheet-proof.json");json.precision(15);json<<"{\"layoutRevision\":2,\"sourceAnatomyVertices\":17528,\"sourceAnatomyTriangles\":35000,\"bodyVertices\":20783,\"vertices\":"<<output.mesh.vertices.size()<<",\"triangles\":"<<output.mesh.triangles.size()<<",\"upperArcRadians\":"<<layout.upperArcRadians<<",\"topSeamVertices\":"<<layout.topSeam.size()<<",\"bottomSeamVertices\":["<<layout.bottomSeams[0].size()<<','<<layout.bottomSeams[1].size()<<"],\"contactBudgetSatisfied\":"<<(output.contactBudgetSatisfied?"true":"false")<<",\"coverageMargin\":"<<output.coverageMargin<<",\"bandTopAttachments\":"<<output.band.topAttachments<<",\"bandBottomAttachments\":"<<output.band.bottomAttachments<<",\"minimumArea\":"<<minimumArea<<",\"degenerateFaces\":"<<flat<<",\"minimumUvArea\":"<<minimumUvArea<<",\"maximumEdge\":"<<maximumEdge<<",\"hemMaximumTurnRadians\":"<<hem.maximumTurnRadians<<",\"hemMaximumCenterOffset\":"<<hem.maximumCenterOffset<<",\"hemMaximumSectionError\":"<<hem.maximumSectionError<<",\"smoothHemBudgetSatisfied\":"<<(smoothHem?"true":"false")<<",\"inputMilliseconds\":"<<inputMs<<",\"fitMilliseconds\":"<<fitMs<<",\"simulate\":false,\"observedGameplay\":false}\n";
 std::cout<<"SOURCE single-sheet contact="<<output.contactBudgetSatisfied<<" margin="<<output.coverageMargin<<" degenerate="<<flat<<" fit="<<fitMs<<"ms sampler="<<inputMs<<"ms\n";Check(output.contactBudgetSatisfied&&output.coverageMargin>=0,"Actual full-source static sheet contact budget failed");Check(!flat,"Actual native cloth has degenerate faces");G::hem_checks::Check(output,parameters,true);return 0;
 }catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 1;}}
