// Actual production D3D9 cloth draw, offscreen in a never-shown disabled window.
// No game launch, focus, keyboard/mouse input, audio or installed-file changes.
#include "../src/runtime/d3d9_proxy.cpp"
#include <iostream>
#define CHECK(x) do{if(!(x)){std::cerr<<"FAIL "<<__LINE__<<" "<<#x<<'\n';return 1;}}while(0)
static unsigned anatomyDraws=0;
static HRESULT STDMETHODCALLTYPE ObserveAnatomyDraw(IDirect3DDevice9* device,D3DPRIMITIVETYPE type,INT base,UINT minv,UINT vertices,UINT start,UINT triangles){
 IDirect3DVertexBuffer9* vb=nullptr;IDirect3DIndexBuffer9* ib=nullptr;UINT offset=0,stride=0;device->GetStreamSource(0,&vb,&offset,&stride);device->GetIndices(&ib);
 bool full=type==D3DPT_TRIANGLELIST&&base==0&&minv==0&&vertices==nrCount&&start==0&&triangles==nrIndexCount/3&&offset==0&&stride==32&&(vb==r14VB||vb==menuTankVB)&&ib==r14IB;
 if(vb)vb->Release();if(ib)ib->Release();if(!full)return E_FAIL;++anatomyDraws;
 // Execute the real hidden HAL draw, rather than substituting a count-only stub.
 return device->DrawIndexedPrimitive(type,base,minv,vertices,start,triangles);
}
static int AdditiveAnatomyGate(IDirect3DDevice9* device){
 using namespace JockstrapAdapter;Release();anatomyScene=0;tankCameraSceneTick=0;renderFrameSerial=100;motionCaptureSerial=100;origDIP=ObserveAnatomyDraw;r14SkinTextureAttempted=true;sharedSkinAttempted=true;
 // Native full-resolution buffers/topology are the production arrays. The
 // offscreen fixture supplies positions; this gate verifies draw ownership,
 // additive lifecycle and full buffer preservation, not artwork or gameplay.
 for(unsigned i=0;i<nrCount;i++){float p[3]={float(i%113)/113-.5f,float(i/113%113)/113-.5f,.5f};memcpy(nrPacked+i*32,p,12);memcpy(nrPacked+i*32+12,nrAttributes+i*20,20);}
 auto anatomy=std::vector<unsigned char>(nrPacked,nrPacked+sizeof(nrPacked));auto title=std::vector<unsigned char>(sizeof(menuTankPacked));memcpy(menuTankPacked,nrPacked,sizeof(menuTankPacked));title.assign(menuTankPacked,menuTankPacked+sizeof(menuTankPacked));
 float shape[7],physics[8];memcpy(shape,sliderValues,sizeof(shape));memcpy(physics,physValues,sizeof(physics));int state=physicsState;shaftNodes[3]={1,2,3};shaftPrevious[3]={.5f,1.5f,2.5f};ballNodes[1]={4,5,6};constraintAccumulator=.004f;constraintSolverReady=true;shaftRestFrameReady=true;
 CHECK(SUCCEEDED(device->CreateVertexBuffer(50915*32,0,0,D3DPOOL_MANAGED,&graftBuffer,nullptr)));CHECK(SUCCEEDED(device->CreateVertexBuffer(sizeof(menuTankPacked),0,0,D3DPOOL_MANAGED,&menuTankVB,nullptr)));void* raw=nullptr;CHECK(SUCCEEDED(menuTankVB->Lock(0,0,&raw,0)));memcpy(raw,menuTankPacked,sizeof(menuTankPacked));menuTankVB->Unlock();
 r14Ready=true;r14UploadPending=true;CHECK(EnsureR14(device));device->SetVertexShader(nullptr);device->SetPixelShader(nullptr);device->SetFVF(D3DFVF_XYZ);device->SetStreamSource(0,graftBuffer,0,32);device->SetIndices(r14IB);CHECK(SUCCEEDED(device->BeginScene()));
 for(unsigned clothing:{0u,1u,0u,1u}){
  SetJockstrapStyle(clothing);CHECK(clothingStyle==clothing);CHECK(memcmp(nrPacked,anatomy.data(),anatomy.size())==0&&memcmp(menuTankPacked,title.data(),title.size())==0);CHECK(memcmp(shape,sliderValues,sizeof(shape))==0&&memcmp(physics,physValues,sizeof(physics))==0&&physicsState==state);CHECK(constraintSolverReady&&shaftRestFrameReady&&constraintAccumulator==.004f&&shaftNodes[3].x==1&&shaftPrevious[3].x==.5f&&ballNodes[1].x==4);
  unsigned before=anatomyDraws;CHECK(SUCCEEDED(HookDIP(device,D3DPT_TRIANGLELIST,0,0,50915,graftTriangleIndexStart,graftTriangleIndexCount/3)));CHECK(anatomyDraws==before+1);CHECK(SUCCEEDED(DrawMenuTank(device,graftBuffer,0,32)));CHECK(anatomyDraws==before+2);
 }
 CHECK(SUCCEEDED(device->EndScene()));CHECK(anatomyDraws==8);ReleaseMenuTank();ReleaseR14();graftBuffer->Release();graftBuffer=nullptr;std::cout<<"PASS additive clothing: Naked/Jockstrap retain all "<<nrCount<<" anatomy vertices/"<<nrIndexCount/3<<" triangles in actual hidden HAL gameplay hook and title draws; controls/physics/source buffers preserved\n";return 0;
}
int main(){using namespace JockstrapAdapter;WNDCLASSA wc{};wc.lpfnWndProc=DefWindowProcA;wc.hInstance=GetModuleHandle(nullptr);wc.lpszClassName="MaleModHiddenGarmentTest";RegisterClassA(&wc);HWND window=CreateWindowExA(0,wc.lpszClassName,"",WS_DISABLED|WS_POPUP,0,0,64,64,nullptr,nullptr,wc.hInstance,nullptr);CHECK(window&&!IsWindowVisible(window));char system[MAX_PATH];GetSystemDirectoryA(system,MAX_PATH);strcat_s(system,"\\d3d9.dll");HMODULE module=LoadLibraryA(system);CHECK(module);auto create=(IDirect3D9* (WINAPI*)(UINT))GetProcAddress(module,"Direct3DCreate9");IDirect3D9* api=create(D3D_SDK_VERSION);CHECK(api);D3DPRESENT_PARAMETERS pp{};pp.Windowed=TRUE;pp.SwapEffect=D3DSWAPEFFECT_DISCARD;pp.hDeviceWindow=window;pp.BackBufferWidth=64;pp.BackBufferHeight=64;pp.BackBufferFormat=D3DFMT_A8R8G8B8;pp.EnableAutoDepthStencil=TRUE;pp.AutoDepthStencilFormat=D3DFMT_D24S8;IDirect3DDevice9* device=nullptr;CHECK(SUCCEEDED(api->CreateDevice(D3DADAPTER_DEFAULT,D3DDEVTYPE_HAL,window,D3DCREATE_SOFTWARE_VERTEXPROCESSING|D3DCREATE_FPU_PRESERVE,&pp,&device)));
 IDirect3DSurface9* target=nullptr;CHECK(SUCCEEDED(device->CreateRenderTarget(64,64,D3DFMT_A8R8G8B8,D3DMULTISAMPLE_NONE,0,FALSE,&target,nullptr)));CHECK(SUCCEEDED(device->SetRenderTarget(0,target)));device->Clear(0,nullptr,D3DCLEAR_TARGET|D3DCLEAR_ZBUFFER,0xff1a3366,1,0);D3DVIEWPORT9 viewport{0,0,64,64,0,1};device->SetViewport(&viewport);
 IDirect3DVertexBuffer9* oldVB=nullptr;IDirect3DIndexBuffer9* oldIB=nullptr;CHECK(SUCCEEDED(device->CreateVertexBuffer(48,0,D3DFVF_XYZ,D3DPOOL_MANAGED,&oldVB,nullptr)));CHECK(SUCCEEDED(device->CreateIndexBuffer(6,0,D3DFMT_INDEX16,D3DPOOL_MANAGED,&oldIB,nullptr)));device->SetStreamSource(0,oldVB,0,12);device->SetIndices(oldIB);device->SetFVF(D3DFVF_XYZ);device->SetRenderState(D3DRS_ALPHABLENDENABLE,TRUE);device->SetRenderState(D3DRS_ZWRITEENABLE,FALSE);device->SetRenderState(D3DRS_CULLMODE,D3DCULL_CW);device->SetRenderState(D3DRS_SRCBLEND,D3DBLEND_ONE);device->SetRenderState(D3DRS_DESTBLEND,D3DBLEND_ZERO);device->SetRenderState(D3DRS_ZFUNC,D3DCMP_LESS);device->SetRenderState(D3DRS_COLORWRITEENABLE,7);device->SetRenderState(D3DRS_SEPARATEALPHABLENDENABLE,FALSE);float originalVS[32],originalPS[4]={.2f,.3f,.4f,.5f};for(float& f:originalVS)f=.77f;device->SetVertexShaderConstantF(0,originalVS,8);device->SetPixelShaderConstantF(0,originalPS,1);IDirect3DVertexDeclaration9* oldDeclaration=nullptr;device->GetVertexDeclaration(&oldDeclaration);
 for(unsigned i=0;i<nrCount;i++)memcpy(nrPacked+i*32+12,nrAttributes+i*20,20);renderFrameSerial=73;tankCameraSceneTick=0;style=G::Style::WhiteJockstrap;ready=true;drawnFrame=-2;for(unsigned section=0;section<3;section++){paletteFrame[section]=73;paletteCount[section]=75;for(unsigned bone=0;bone<75;bone++){auto* m=palettes[section]+bone*12;memset(m,0,48);m[0]=m[5]=m[10]=1;}}memset(localMatrix,0,64);memset(viewMatrix,0,64);for(unsigned i=0;i<4;i++){localMatrix[i*5]=1;viewMatrix[i*5]=1;}
 auto cloth=std::make_shared<G::Output>();cloth->style=style;for(unsigned material=0;material<4;material++){double x=(material%2)?.5:-.5,y=(material/2)?.5:-.5;unsigned base=(unsigned)cloth->mesh.vertices.size();for(auto p:{G::Point{x-.4,y-.4,.5},G::Point{x+.4,y-.4,.5},G::Point{x,y+.4,.5}}){G::Vertex v;v.position=p;v.normal={0,0,1};v.uv={.125,.25};v.lineage.donors[0]={G::Surface::Anatomy,5000,1};cloth->mesh.vertices.push_back(v);}cloth->mesh.triangles.push_back({{base,base+1,base+2},G::MaterialSlot(material)});}// A hidden rear cloth layer must not turn .95 coverage into .9975.
 auto frontVertices=cloth->mesh.vertices;auto frontTriangles=cloth->mesh.triangles;
 for(auto v:frontVertices){v.position[2]=.7;cloth->mesh.vertices.push_back(v);}
 for(auto triangle:frontTriangles){for(auto& i:triangle.vertices)i+=(unsigned)frontVertices.size();cloth->mesh.triangles.push_back(triangle);}
 for(unsigned section=0;section<3;section++){memcpy(sectionLocal[section],localMatrix,64);memcpy(sectionView[section],viewMatrix,64);}fluidWorldCameraFrame=73;fluidCameraWorld={};auto coherent=std::make_shared<JockstrapCpuWorker::Delivery>();coherent->output=cloth;coherent->pose=CapturePose(73);CHECK(coherent->pose);solved=coherent;snapshot=cloth;latest=snapshot.get();CHECK(SUCCEEDED(device->BeginScene()));Draw(device);CHECK(SUCCEEDED(device->EndScene()));CHECK(drawnFrame==73);
 DWORD state;device->GetRenderState(D3DRS_ALPHABLENDENABLE,&state);CHECK(state==TRUE);device->GetRenderState(D3DRS_ZWRITEENABLE,&state);CHECK(state==FALSE);device->GetRenderState(D3DRS_CULLMODE,&state);CHECK(state==D3DCULL_CW);device->GetRenderState(D3DRS_SRCBLEND,&state);CHECK(state==D3DBLEND_ONE);device->GetRenderState(D3DRS_DESTBLEND,&state);CHECK(state==D3DBLEND_ZERO);device->GetRenderState(D3DRS_ZFUNC,&state);CHECK(state==D3DCMP_LESS);device->GetRenderState(D3DRS_COLORWRITEENABLE,&state);CHECK(state==7);device->GetRenderState(D3DRS_SEPARATEALPHABLENDENABLE,&state);CHECK(state==FALSE);float constants[32];device->GetVertexShaderConstantF(0,constants,8);CHECK(memcmp(constants,originalVS,128)==0);device->GetPixelShaderConstantF(0,constants,1);CHECK(memcmp(constants,originalPS,16)==0);IDirect3DVertexBuffer9* restoredVB;UINT offset,stride;device->GetStreamSource(0,&restoredVB,&offset,&stride);CHECK(restoredVB==oldVB&&offset==0&&stride==12);restoredVB->Release();IDirect3DIndexBuffer9* restoredIB;device->GetIndices(&restoredIB);CHECK(restoredIB==oldIB);restoredIB->Release();IDirect3DVertexDeclaration9* restoredDeclaration;device->GetVertexDeclaration(&restoredDeclaration);CHECK(restoredDeclaration==oldDeclaration);restoredDeclaration->Release();oldDeclaration->Release();
 IDirect3DSurface9* readback=nullptr;CHECK(SUCCEEDED(device->CreateOffscreenPlainSurface(64,64,D3DFMT_A8R8G8B8,D3DPOOL_SYSTEMMEM,&readback,nullptr)));CHECK(SUCCEEDED(device->GetRenderTargetData(target,readback)));D3DLOCKED_RECT pixels;CHECK(SUCCEEDED(readback->LockRect(&pixels,nullptr,D3DLOCK_READONLY)));auto color=[&](unsigned x,unsigned y){return ((DWORD*)((unsigned char*)pixels.pBits+y*pixels.Pitch))[x];};for(unsigned material=0;material<4;material++){unsigned x=(material%2)?48:16,y=(material/2)?16:48;DWORD c=color(x,y);unsigned red=(c>>16)&255,green=(c>>8)&255,blue=c&255;double knit=1+.018*std::cos(.125*804.2477)+.004*std::cos(.25*1608.4954);double lighting=.76+.24*.76/std::sqrt(.35*.35+.55*.55+.76*.76);const double background[3]={26,51,102};unsigned channels[3]={(c>>16)&255,(c>>8)&255,c&255};for(unsigned channel=0;channel<3;channel++){double expected=.95*cloth->materials[material].color[channel]*knit*lighting*255+.05*background[channel];CHECK(std::abs(double(channels[channel])-expected)<=2.0);}if(material<2)CHECK(red>170&&green>170&&blue>170);if(material==2)CHECK(red>green*3&&red>blue*3);if(material==3)CHECK(blue>red*3&&blue>green*2);}CHECK((color(48,6)&0xffffff)!=0x1a3366);CHECK(color(0,0)==0xff1a3366);readback->UnlockRect();CHECK(!IsWindowVisible(window));CHECK(AdditiveAnatomyGate(device)==0);Release();readback->Release();target->Release();oldVB->Release();oldIB->Release();device->Release();api->Release();DestroyWindow(window);std::cout<<"PASS actual production D3D9 95% single-surface opacity over retained background with overlapping rear cloth, four materials, last vertex coverage and complete stream/index/declaration/constants/render-state restoration; hidden offscreen HAL\n";return 0;}
