"""Offline endpoint reduction and complete runtime binding compaction.

Inputs are immutable gzip authoring archives, not included by the game build.
No decimation, remapping, or high-resolution safety skin runs in-game.
Run: python tools/remesh/compact_runtime.py generate|apply
"""
from pathlib import Path
import argparse, gzip, hashlib, json, re, time
import numpy as np
from scipy.sparse import csr_matrix
from scipy.linalg import lstsq
from endpoint_qem import QEMDecimator

HERE=Path(__file__).resolve().parent
ROOT=HERE.parents[1]
RUNTIME=ROOT/'src/runtime'
CAPTURES=ROOT/'captures/surface-audit-revised'
ARRAY=re.compile(r'(static (?:const|constexpr)\s+([\w ]+?)\s+(\w+))\[(\d+)\]\s*=\s*\{(.*?)\};',re.S)

class Header:
    def __init__(self,name):
        self.name=name
        self.text=gzip.decompress((HERE/'baseline'/f'{name}.gz').read_bytes()).decode('utf-8').replace('\r\n','\n')
        self.matches={m[3]:m for m in ARRAY.finditer(self.text)}
        self.edits={}
        self.constants={}
    def a(self,name,dtype=np.int64):
        m=self.matches[name]
        s=re.sub(r'(?<=\d)[fF]\b','',m[5])
        a=np.fromstring(s.replace('\n','').replace('\r',''),sep=',',dtype=np.float64)
        assert len(a)==int(m[4]),(name,len(a),m[4])
        return a.astype(dtype)
    def c(self,name):
        return int(re.search(r'\b'+name+r'\s*=\s*(\d+)',self.text)[1])
    def set(self,name,value):self.edits[name]=np.asarray(value).ravel()
    def count(self,name,value):self.constants[name]=int(value)
    def write(self):
        s=self.text
        for name,a in self.edits.items():
            m=self.matches[name];typ=m[2].strip()
            if typ in ('float','double'):
                vals=[format(float(v),'.9e')+('f' if typ=='float' else '') for v in a]
            else:vals=[str(int(v)) for v in a]
            content=',\n'.join(','.join(vals[i:i+18]) for i in range(0,len(vals),18))
            replacement=f'{m[1]}[{len(a)}]={{\n{content}\n}};'
            s=s.replace(m[0],replacement,1)
        for name,v in self.constants.items():
            s,n=re.subn(r'\b'+name+r'\s*=\s*\d+',name+'='+str(v),s,count=1)
            assert n==1,name
        s=s.replace('#pragma once','#pragma once\n// Generated by tools/remesh/compact_runtime.py; compact runtime topology.',1)
        (RUNTIME/self.name).write_text(s,encoding='utf-8')

def headers():return {n:Header(n+'.h') for n in ['rounded_render_data','pouch_surface_data','geometry_binding_data','neck_render_data','unified_collar_data','pelvic_attachment_data']}

def capture(path):
    raw=path.read_bytes();base=50059*28
    def points(n,off):return np.ndarray((n,3),np.float32,buffer=raw,offset=off,strides=(32,4)).astype(np.float64)
    return points(30717,base),points(26750,base+30717*32)

def representatives(dec):
    p=dec.parent.copy()
    for i in range(len(p)):
        k=i
        while p[k]!=k:k=int(p[k])
        p[i]=k
    return p

class PoseQEM(QEMDecimator):
    def __init__(self,poses,faces,locks,attrs,radius=.70):
        self.poses=poses
        self.extra_locks=locks
        self.attrs=attrs
        self.collapses=0
        t=poses[:,faces]
        self.originalNormals=np.cross(t[:,:,1]-t[:,:,0],t[:,:,2]-t[:,:,0])
        super().__init__(poses[0],faces,np.zeros(len(poses[0])),np.zeros(len(poses[0])),radius)
    def _init_locks(self,mask):
        self.locked |= self.extra_locks
        super()._init_locks(mask)
    def _collapse_valid(self,u,v,keep,group):
        # Never cross materially different skinning or texture coordinates.
        if self.attrs is not None:
            if np.sum(np.abs(self.attrs[u,:5]-self.attrs[v,:5]))>.24:return False
            if np.max(np.abs(self.attrs[u,5:]-self.attrs[v,5:]))>.08:return False
        if not super()._collapse_valid(u,v,keep,group):return False
        remove=v if keep==u else u
        ids=[i for i in self.vertex_faces[remove] if keep not in self.f[i]]
        if not ids:return True
        old=self.f[ids];new=old.copy();new[new==remove]=keep
        p=self.poses[1:]
        a=p[:,old];b=p[:,new]
        n=self.originalNormals[1:,ids];q=np.cross(b[:,:,1]-b[:,:,0],b[:,:,2]-b[:,:,0])
        nn=np.linalg.norm(n,axis=2);qq=np.linalg.norm(q,axis=2)
        valid=(nn<1e-9)|((qq>1e-10)&(np.sum(n*q,axis=2)>=.25*nn*qq))
        return bool(np.all(valid))
    def _do_collapse(self,*args):
        super()._do_collapse(*args)
        self.collapses+=1
        if self.collapses%500==0:print(f'  {self.active_faces} faces, {self.collapses} collapses',flush=True)

def feature_locks(h,kind,p,faces):
    locks=np.zeros(len(p),bool)
    if kind=='nr':
        u=h['unified_collar_data'];m=u.a('ucMap');k=u.a('ucKeep');seam=u.a('ucSeamVertices')
        facesUC=u.a('ucFaces').reshape(-1,3)
        bodyFaces=facesUC[~np.all(np.isin(facesUC,np.unique(m[:30717])),axis=1)]
        required=np.unique(np.r_[m[30717:],seam,bodyFaces.ravel()])
        locks[np.isin(m[:30717],required)]=True
        requiredPacked=k[seam];locks[requiredPacked[requiredPacked<30717]]=True
        if (HERE/'nr-safety-locks.json').exists():locks[json.loads((HERE/'nr-safety-locks.json').read_text())['vertices']]=True
    else:
        locks[h['pelvic_attachment_data'].a('paSeamR14')]=True
        locks[json.loads((HERE/'rs-safety-locks.json').read_text())['vertices']]=True
    # Authoring feature creases are protected independently of triangle density.
    normals=np.cross(p[faces[:,1]]-p[faces[:,0]],p[faces[:,2]]-p[faces[:,0]])
    lengths=np.linalg.norm(normals,axis=1);normals/=np.maximum(lengths[:,None],1e-12)
    e=np.sort(np.concatenate([faces[:,[0,1]],faces[:,[1,2]],faces[:,[2,0]]]),axis=1)
    ids=np.tile(np.arange(len(faces)),3);order=np.lexsort((e[:,1],e[:,0]));e=e[order];ids=ids[order]
    shared=np.all(e[:-1]==e[1:],axis=1)
    dot=np.einsum('ij,ij->i',normals[ids[:-1]],normals[ids[1:]])
    sharp=shared&(dot<np.cos(np.deg2rad(48)))&(lengths[ids[:-1]]>1e-8)&(lengths[ids[1:]]>1e-8)
    locks[np.unique(e[:-1][sharp])]=True
    return locks

def nr_attributes(h):
    a=h['neck_render_data'].a('nrAttributes').astype(np.uint8).reshape(-1,20)
    out=np.zeros((len(a),7),float)
    # Packed tangent/normal occupy eight bytes, followed by bones/weights/UV.
    for j in range(4):
        b=a[:,8+j];w=a[:,12+j]/255.
        assert b.max()<5
        np.add.at(out,(np.arange(len(a)),b),w)
    out[:,5:]=a[:,16:20].copy().view(np.float16).reshape(-1,2).astype(float)
    return out

def generate():
    h=headers();paths=sorted(CAPTURES.glob('*.bin'))
    assert len(paths)==88, 'The baseline pose bank must contain all 88 fixtures'
    captures=[capture(p) for p in paths];out={};reports={}
    for kind,idx,name,target in [('rs',1,'rounded_render_data',32000),('nr',0,'neck_render_data',35000)]:
        poses=np.stack([p[idx] for p in captures]);faces=h[name].a(kind+'Indices').reshape(-1,3)
        locks=feature_locks(h,kind,poses[0],faces)
        d=PoseQEM(poses,faces,locks,nr_attributes(h) if kind=='nr' else None)
        d.simplify_group(0,target)
        f,lineage,report=d.result();rep=representatives(d)
        out[kind+'_faces']=f;out[kind+'_lineage']=lineage;out[kind+'_rep']=rep;out[kind+'_locked']=d.locked
        reports[kind]=report;print(kind,report,flush=True)
    np.savez_compressed(HERE/'candidate.npz',**out)
    (HERE/'candidate-report.json').write_text(json.dumps({'poses':[p.name for p in paths],'reports':reports},indent=2))

def coalesce(rows,sources,weights,selected,mapping):
    # Retain original donor accumulation order. Merge only identical donors.
    rr=[0];ss=[];ww=[]
    for i in selected:
        merged={}
        for j in range(rows[i],rows[i+1]):
            s=int(mapping[sources[j]]);assert s>=0
            merged[s]=merged.get(s,0.)+weights[j]
        for s,w in merged.items():
            if w!=0:ss.append(s);ww.append(w)
        rr.append(len(ss))
    return np.array(rr),np.array(ss),np.array(ww,np.float32)

def transport_donors(h,rkeep):
    """Eliminate redundant fine donors using affine local frame coordinates.

    Only data is baked: no extra interpolation layer is evaluated at runtime.
    Preserve a donor outright if the local fit cannot reproduce all fixtures.
    """
    rs=h['rounded_render_data'];g=h['geometry_binding_data']
    frames=g.a('geometryFineFrames').reshape(-1,3);ids=g.a('geometryFineFrameIDs')
    poses=np.stack([capture(p)[1] for p in sorted(CAPTURES.glob('*.bin'))])
    keepSet=set(map(int,rkeep));sub={};restored=[];errors=[]
    for i in range(10554,26750):
        if i in keepSet:continue
        frame=ids[i-10554]
        siblings=np.flatnonzero(ids==frame)+10554
        local=np.unique(np.r_[frames[frame],[s for s in siblings if int(s) in keepSet]]).astype(int)
        base=poses[:,local[0]];mat=(poses[:,local[1:]]-base[:,None]).transpose(0,2,1).reshape(-1,len(local)-1)
        rhs=(poses[:,i]-base).ravel()
        coeff=lstsq(mat,rhs,cond=1e-7,lapack_driver='gelsy')[0];w=np.r_[1-coeff.sum(),coeff]
        fitted=np.einsum('pvc,v->pc',poses[:,local],w);err=float(np.linalg.norm(fitted-poses[:,i],axis=1).max())
        if err>.002 or np.abs(w).sum()>8:
            restored.append(i);keepSet.add(i)
        else:
            valid=np.abs(w)>1e-8;sub[i]=(local[valid],w[valid]);errors.append(err)
    (HERE/'donor-transport.json').write_text(json.dumps({'eliminatedFineDonors':len(sub),'restoredFineDonors':len(restored),'maximumFixtureError':max(errors,default=0.)},indent=2))
    return np.unique(np.r_[rkeep,restored]),sub

def transport_rows(rows,sources,weights,selected,compact,sub):
    rr=[0];ss=[];ww=[]
    for i in selected:
        merged={}
        for j in range(rows[i],rows[i+1]):
            s=int(sources[j]);w=weights[j]
            ids,coeff=sub.get(s,(np.array([s]),np.array([1.])))
            for k,v in zip(ids,coeff):
                new=int(compact[k]);assert new>=0
                merged[new]=merged.get(new,0.)+w*v
        for s,w in merged.items():
            if abs(w)>1e-10:ss.append(s);ww.append(w)
        rr.append(len(ss))
    return np.array(rr),np.array(ss),np.array(ww,np.float32)

def apply():
    h=headers();d=np.load(HERE/'candidate.npz')
    rs=h['rounded_render_data'];cp=h['pouch_surface_data'];g=h['geometry_binding_data'];nr=h['neck_render_data'];uc=h['unified_collar_data']
    r14=10554;oldRS=26750;oldNR=30717
    rf=d['rs_faces'];nf=d['nr_faces'];rrep=d['rs_rep'];nrep=d['nr_rep']
    # All coarse cage entries retain their indexing; only necessary fine endpoints remain.
    survivingRS=np.unique(rf)
    # Preserve the established pressure/diffusion field as a compact point cage.
    # Its support nodes are not a second render or collision mesh. Pruning them
    # independently changed diffusion lengths and folded small bound faces.
    oldFair=cp.a('cpFair');oldRows=cp.a('cpRows');oldNeighbors=cp.a('cpNeighbors')
    fieldSupport=np.unique(np.r_[cp.a('cpActive'),oldFair,cp.a('cpNeckIDs'),cp.a('cpNeckSources'),np.concatenate([oldNeighbors[oldRows[i]:oldRows[i+1]] for i in oldFair])])
    requiredDirect=nr.a('nrDirect')[np.unique(nf)];requiredDirect=requiredDirect[requiredDirect!=65535]
    rkeep=np.unique(np.r_[np.arange(r14),survivingRS,fieldSupport,requiredDirect])
    rkeep,substitutions=transport_donors(h,rkeep)
    rrep=rrep.copy();rrep[rkeep]=rkeep
    rc=np.full(oldRS,-1,int);rc[rkeep]=np.arange(len(rkeep));rm=rc[rrep]
    assert np.all(rm>=0)
    nkeep=np.unique(nf);nc=np.full(oldNR,-1,int);nc[nkeep]=np.arange(len(nkeep))
    rs.set('rsIndices',rc[rf]);rs.set('rsFaceParent',rs.a('rsFaceParent')[d['rs_lineage']])
    rs.count('rsCount',len(rkeep));rs.count('rsFineCount',len(rkeep)-r14);rs.count('rsIndexCount',rf.size)
    fine=rkeep[r14:]-r14
    for name in ['rsFineSource','rsFineBary','rsFineCoeff']:
        rs.set(name,rs.a(name,np.float64).reshape(-1,3)[fine])
    rs.set('rsFineLobeFade',rs.a('rsFineLobeFade',float)[fine])
    # These normal lists are authoring metadata; compact them as well.
    normal=np.unique(rm[rs.a('rsNormalIDs')]);rs.set('rsNormalIDs',normal);rs.count('rsNormalCount',len(normal))
    normalFaces=np.flatnonzero(np.any(np.isin(rc[rf],normal),axis=1))
    rs.set('rsNormalFaces',rc[rf][normalFaces]);rs.count('rsNormalFaceCount',len(normalFaces))
    frameIDs=g.a('geometryFineFrameIDs')[fine];frames=np.unique(frameIDs);fc=np.full(g.c('geometryFineFrameCount'),-1,int);fc[frames]=np.arange(len(frames))
    g.set('geometryFineFrames',g.a('geometryFineFrames').reshape(-1,3)[frames]);g.set('geometryFineFrameIDs',fc[frameIDs]);g.count('geometryFineFrameCount',len(frames))
    g.set('geometryFineFaces',3*np.flatnonzero(np.any(rc[rf]>=r14,axis=1)))
    # Restrict surface work to endpoints that survived the topology reduction.
    for key,arrays in [('Active',['cpWeights','cpDirections']),('Fair',['cpFairWeight'])]:
        ids=cp.a('cp'+key);selected=np.flatnonzero(np.isin(ids,rkeep));newids=rc[ids[selected]]
        cp.set('cp'+key,newids);cp.count('cp'+key+'Count',len(newids))
        for name in arrays:
            a=cp.a(name,float);stride=len(a)//len(ids);cp.set(name,a.reshape(-1,stride)[selected])
    rows=[0];neighbors=[];fairSet=set(map(int,oldFair))
    for i in rkeep:
        if int(i) in fairSet:neighbors.extend(rm[oldNeighbors[oldRows[i]:oldRows[i+1]]])
        rows.append(len(neighbors))
    cp.set('cpRows',rows);cp.set('cpNeighbors',neighbors)
    cp.set('cpReference',cp.a('cpReference',float).reshape(-1,3)[rkeep])
    ids=cp.a('cpNeckIDs');selected=np.flatnonzero(np.isin(ids,rkeep))
    rr,ss,ww=coalesce(cp.a('cpNeckRows'),cp.a('cpNeckSources'),cp.a('cpNeckWeights',float),selected,rm)
    cp.set('cpNeckIDs',rc[ids[selected]]);cp.set('cpNeckRows',rr);cp.set('cpNeckSources',ss);cp.set('cpNeckWeights',ww);cp.set('cpNeckBlend',cp.a('cpNeckBlend',float)[selected]);cp.count('cpNeckCount',len(selected))
    normal=np.unique(rm[cp.a('cpNormalIDs')]);cp.set('cpNormalIDs',normal);cp.count('cpNormalCount',len(normal))
    normalFaces=np.flatnonzero(np.any(np.isin(rc[rf],normal),axis=1));cp.set('cpNormalFaces',rc[rf][normalFaces]);cp.count('cpNormalFaceCount',len(normalFaces))
    # Final render, collider and splat triangles share exactly this index buffer.
    nr.set('nrIndices',nc[nf]);nr.count('nrCount',len(nkeep));nr.count('nrIndexCount',nf.size)
    direct=nr.a('nrDirect')[nkeep];newDirect=np.full(len(nkeep),65535,int);valid=direct!=65535
    valid &= np.where(direct==65535,False,rrep[np.minimum(direct,oldRS-1)]==direct)
    valid &= np.isin(direct,survivingRS)
    newDirect[valid]=rm[direct[valid]]
    nr.set('nrDirect',newDirect)
    rr,ss,ww=transport_rows(nr.a('nrRows'),nr.a('nrSources'),nr.a('nrWeights',float),nkeep,rc,substitutions)
    nr.set('nrRows',rr);nr.set('nrSources',ss);nr.set('nrWeights',ww)
    nr.set('nrAttributes',nr.a('nrAttributes').reshape(-1,20)[nkeep])
    nr.set('nrMaterialSources',rm[nr.a('nrMaterialSources').reshape(-1,3)[nkeep]])
    nr.set('nrMaterialWeights',nr.a('nrMaterialWeights',float).reshape(-1,3)[nkeep])
    mix=nr.a('nrNormalMix',float)[nkeep];mix[(direct!=65535)&~valid]=1.
    mix[np.any(~np.isin(nr.a('nrMaterialSources').reshape(-1,3)[nkeep],survivingRS),axis=1)]=1.
    nr.set('nrNormalMix',mix)
    # Replace anatomy faces in the joined domain; retain all original body faces.
    um=uc.a('ucMap');uk=uc.a('ucKeep');uf=uc.a('ucFaces').reshape(-1,3);seams=uc.a('ucSeamVertices').reshape(-1,3)
    isAnatomy=np.all(np.isin(uf,np.unique(um[:oldNR])),axis=1)
    # The joined collar uses outward winding, opposite to the render indices.
    # Preserve that convention: its forward cross product writes lighting normals.
    joined=np.r_[uf[~isAnatomy],um[nf[:,[0,2,1]]]]
    nodes=np.unique(np.r_[joined.ravel(),seams.ravel(),um[nkeep],um[oldNR:]])
    ucCompact=np.full(uc.c('ucCount'),-1,int);ucCompact[nodes]=np.arange(len(nodes))
    newMap=ucCompact[np.r_[um[nkeep],um[oldNR:]]]
    packed=uk[nodes];newKeep=np.where(packed<oldNR,nc[np.minimum(packed,oldNR-1)],len(nkeep)+packed-oldNR)
    # A UV duplicate can survive after the old representative is collapsed.
    # Select its surviving packed alias; the joined node is still identical.
    _,first=np.unique(newMap,return_index=True)
    lost=newKeep<0;newKeep[lost]=first[lost]
    assert np.all(newKeep>=0),'A protected weld vertex was removed'
    assert np.array_equal(newMap[newKeep],np.arange(len(nodes)))
    edges=np.sort(np.r_[joined[:,[0,1]],joined[:,[1,2]],joined[:,[2,0]]],axis=1);_,counts=np.unique(edges,axis=0,return_counts=True)
    assert np.all(counts<=2),'Nonmanifold joined mesh'
    uc.set('ucKeep',newKeep);uc.set('ucMap',newMap);uc.set('ucFaces',ucCompact[joined]);uc.set('ucSeamVertices',ucCompact[seams])
    uc.count('ucCount',len(nodes));uc.count('ucPackedCount',len(newMap));uc.count('ucFaceCount',len(joined))
    # Bound binding drift across every saved deformation before writing source.
    oldRows=nr.a('nrRows');oldSources=nr.a('nrSources');oldWeights=nr.a('nrWeights',float)
    a=csr_matrix((oldWeights,oldSources,oldRows),shape=(oldNR,oldRS))[nkeep]
    b=csr_matrix((ww,ss,rr),shape=(len(nkeep),len(rkeep)))
    errors=[]
    for path in sorted(CAPTURES.glob('*.bin')):
        _,p=capture(path);delta=b@p[rkeep]-a@p
        errors.append((path.name,float(np.linalg.norm(delta,axis=1).max()),float(np.sqrt(np.mean(delta**2)))))
    print('binding max',max(errors,key=lambda x:x[1]),flush=True)
    report={'nrVertices':len(nkeep),'nrTriangles':len(nf),'rsVertices':len(rkeep),'rsTriangles':len(rf),'cpActive':len(cp.edits['cpActive']),'cpFair':len(cp.edits['cpFair']),'cpNeighborLinks':len(neighbors),'cpNeckSources':len(cp.edits['cpNeckSources']),'nrSources':len(ss),'ucNodes':len(nodes),'ucFaces':len(joined),'bindingErrors':errors}
    # Save explicit remaps only in authoring outputs, never a runtime shadow skin.
    np.savez_compressed(HERE/'remaps.npz',rsKeep=rkeep,rsRemap=rm,nrKeep=nkeep,nrRemap=nc[nrep],ucKeep=nodes)
    (HERE/'compact-report.json').write_text(json.dumps(report,indent=2))
    for name in ['rounded_render_data','pouch_surface_data','geometry_binding_data','neck_render_data','unified_collar_data']:h[name].write()
    print(json.dumps({k:v for k,v in report.items() if k!='bindingErrors'},indent=2),flush=True)

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('operation',choices=['generate','apply']);args=p.parse_args()
    {'generate':generate,'apply':apply}[args.operation]()
