from pathlib import Path
import numpy as np
r=Path(__file__).resolve().parent/'authoring';d=dict(np.load(r/'render-bindings.npz'));src=np.fromfile(r/'base.vertices',np.uint8).reshape(-1,32);N=len(d['direct']);mat=d['materialSources'];bary=d['materialWeights'];attributes=np.zeros((N,20),np.uint8)
for i in range(N):
 ids=mat[i];w=bary[i];attributes[i]=src[ids[w.argmax()],12:]
 uv=np.sum(src[ids,28:32].copy().view('<f2').reshape(3,2).astype(float)*w[:,None],axis=0);attributes[i,16:20]=uv.astype('<f2').view(np.uint8)
 weights=np.zeros(256)
 for j in range(3):
  for b in range(4):weights[src[ids[j],20+b]]+=w[j]*src[ids[j],24+b]
 bones=np.argsort(weights)[-4:][::-1];values=weights[bones];values/=values.sum();packed=np.round(values*255).astype(int);packed[0]+=255-packed.sum();bones[packed==0]=0;attributes[i,8:12]=bones;attributes[i,12:16]=packed
# Parameterize the replacement annulus continuously from the preserved skin boundary.
# Closest-face UVs alone have a discontinuity at the old neck/shaft medial axis.
from scipy import sparse
from scipy.sparse.linalg import spsolve
Q=d['rest'];F=d['indices'];edges=np.vstack((F[:,[0,1]],F[:,[1,2]],F[:,[2,0]]));edges=np.unique(np.sort(edges,axis=1),axis=0);ew=1/np.maximum(np.linalg.norm(Q[edges[:,0]]-Q[edges[:,1]],axis=1),.02)
A=sparse.coo_matrix((np.r_[ew,ew],(np.r_[edges[:,0],edges[:,1]],np.r_[edges[:,1],edges[:,0]])),shape=(N,N)).tocsr();degree=np.asarray(A.sum(1)).ravel();L=sparse.diags(degree)-A
outside=int(np.load(r/'stitched-meta.npz')['originalOutsideCount']);free=np.where((np.arange(N)>=outside)&(d['direct']<0))[0];fixed=np.setdiff1d(np.arange(N),free)
uv=attributes[:,16:20].copy().view('<f2').reshape(-1,2).astype(float);uv[free]=np.load(r/'uv-guide.npy')[free];anchor=.025*degree[free]
uv[free]=spsolve(L[free][:,free]+sparse.diags(anchor),-L[free][:,fixed]@uv[fixed]+anchor[:,None]*uv[free]);attributes[:,16:20]=uv.astype('<f2').view(np.uint8).reshape(-1,4)
attributes.tofile(r/"render-attributes.bin")
rows=[0];ss=[];ww=[]
for i in range(N):
 if d['direct'][i]>=0:ids=[int(d['direct'][i])];weights=[1.]
 else:
  ids=d['sources'][i];weights=d['weights'][i];keep=abs(weights)>1e-8;ids=ids[keep];weights=weights[keep];weights=weights/weights.sum()
 ss.extend(ids);ww.extend(weights);rows.append(len(ss))
path=Path(__file__).resolve().parents[2]/'src/runtime/neck_render_data.h'
with path.open('w') as f:
 f.write('#pragma once\n// Generated by tools/neck/export_neck.py from the approved local junction rebuild.\n')
 f.write(f'static const unsigned nrCount={N},nrIndexCount={d["indices"].size};\n')
 def arr(type,name,a,fmt=str):
  a=np.asarray(a).ravel();f.write(f'static const {type} {name}[{len(a)}]={{\n')
  for start in range(0,len(a),24):f.write(','.join(fmt(x) for x in a[start:start+24])+',\n')
  f.write('};\n')
 arr('unsigned short','nrIndices',d['indices']);arr('unsigned short','nrDirect',np.where(d['direct']<0,65535,d['direct']));arr('unsigned','nrRows',rows);arr('unsigned short','nrSources',ss);arr('float','nrWeights',ww,lambda x:f'{x:.9e}f');arr('unsigned char','nrAttributes',attributes);arr('unsigned short','nrMaterialSources',mat);arr('float','nrMaterialWeights',bary,lambda x:f'{x:.9e}f');arr('float','nrNormalMix',d['normalMix'],lambda x:f'{x:.9e}f')
print('render data',N,'verts',len(ss),'binding terms',path.stat().st_size,'bytes')
