#define main ThreadReferenceMain
#include "thread_test.cpp"
#undef main
#include <d3d9.h>
#include <d3dx9.h>
static bool FluidProjectSplat(const volumeFluid::FluidImpact&,V3,volumeFluid::FluidImpact&){return false;}
static bool FluidResolveSplat(const volumeFluid::FluidImpact&,V3&,V3&){return false;}
#define SPLAT_SHADER_COMPILER
#include "../../src/runtime/fluid_stains.h"
int main(int argc,char** argv){
 if(argc!=2)return 2;FILE* f=nullptr;if(fopen_s(&f,argv[1],"wb")||!f)return 3;
 fprintf(f,"#pragma once\n// Generated by tools/fluid/compile_splat_shader.cpp. Do not edit.\n");
 for(int i=0;i<2;i++){
  ID3DXBuffer *code=nullptr,*errors=nullptr;DWORD start=GetTickCount();
  HRESULT hr=D3DXCompileShader(volumeFluid::stainShader,(UINT)strlen(volumeFluid::stainShader),nullptr,nullptr,i?"Pixel":"Vertex",i?"ps_3_0":"vs_3_0",D3DXSHADER_OPTIMIZATION_LEVEL3,&code,&errors,nullptr);
  if(errors){printf("%s\n",(const char*)errors->GetBufferPointer());errors->Release();}
  if(FAILED(hr)||!code){fclose(f);return 4;}
  printf("BUILD ONLY %s shader compilation: %lu ms, %lu bytes\n",i?"pixel":"vertex",GetTickCount()-start,code->GetBufferSize());
  fprintf(f,"static const DWORD %s[]={\n",i?"stainPixelBytecode":"stainVertexBytecode");
  auto words=(const DWORD*)code->GetBufferPointer();for(DWORD n=0;n<code->GetBufferSize()/4;n++)fprintf(f,"0x%08lXu,%s",words[n],n%8==7?"\n":"");fprintf(f,"\n};\n");code->Release();
 }fclose(f);return 0;
}
