import sys
from pathlib import Path


from ramp_mesh_data import *
def smooth(x):
 x=np.clip(x,0,1);return x*x*x*(x*(6*x-15)+10)
def relief(p):
 x,y,z=p.T
 # One medial surface strip wraps around the pouch and onto the perineum.
 # The posterior and upper limits fade inside the existing controlled pelvis.
 return .30*np.exp(-(y/.70)**2)*smooth((x-2.0)/5.0)*(1-smooth((z-79.8)/2.4))*(1-smooth((x-15)/7))
def emit(name,a,kind='float'):
 vals=[f'{v:.9e}f' if kind=='float' else str(int(v)) for v in np.asarray(a).ravel()]
 return f'static const {kind} {name}[{len(vals)}]={{\n'+',\n'.join(','.join(vals[i:i+12]) for i in range(0,len(vals),12))+'\n};\n'
rbase=arr('r14_asset.h','r14Base').reshape(-1,3)
rt=arr('r14_asset.h','r14Indices',int).reshape(-1,3)
x,y,z=rbase.T
mask=smooth((x-12.4)/2)*(1-smooth((x-20)/3))*smooth((z-74)/3)*(1-smooth((z-80)/2))*np.exp(-(y/2.0)**4)
neighbors=[set() for _ in rbase]
for a,b,c in rt:
 neighbors[a].update([b,c]);neighbors[b].update([a,c]);neighbors[c].update([a,b])
active=np.flatnonzero(mask>1e-4)
offset=[0];indices=[]
for i in active:indices.extend(sorted(neighbors[i]));offset.append(len(indices))
text='// Generated by tools/Generate-ContinuousRaphe.py: continuous external midline relief.\n#pragma once\n'
text+=emit('rapheGraft',relief(base))+emit('rapheCollar',relief(groupbase))
from scipy.spatial import cKDTree
pool=np.vstack([base,groupbase]);tree=cKDTree(pool)
field_rows=[0];field_ids=[];field_weights=[]
for p in pool:
 ns=sorted(tree.query_ball_point(p,3.0));d=np.linalg.norm(pool[ns]-p,axis=1)
 w=(1-smooth(d/3.0))**2;w/=w.sum()
 field_ids.extend(ns);field_weights.extend(w);field_rows.append(len(field_ids))
text+=emit('rapheFieldRows',field_rows,'unsigned')+emit('rapheFieldIDs',field_ids,'unsigned')+emit('rapheFieldWeights',field_weights)
text+=emit('rapheSmoothIDs',active,'unsigned')+emit('rapheSmoothOffsets',offset,'unsigned')+emit('rapheSmoothNeighbors',indices,'unsigned')+emit('rapheSmoothMask',mask[active])
text+=emit('rapheSmoothFull',mask)
text+=f'static const unsigned rapheSmoothCount={len(active)};\n'
(SRC/'continuous_raphe_data.h').write_text(text)
print('smoothing',len(active),'relief graft',int((relief(base)>1e-4).sum()),'collar',int((relief(groupbase)>1e-4).sum()))
print('uncontrolled body',len(set(members[members<47050])-set(pi)))
assert not [g for g in range(len(groupbase)) if relief(groupbase)[g]>1e-7 and any(i<47050 and i not in set(pi) for i in members[offsets[g]:offsets[g+1]])]
