from ramp_mesh_data import *
from scipy import sparse
from scipy.sparse.linalg import splu
n=len(groupbase)
edges=[]; vals=[]; deg=[]
for i in range(n):
    ns=neighbors[noff[i]:noff[i+1]]
    w=1/np.maximum(np.linalg.norm(groupbase[ns]-groupbase[i],axis=1),.25)
    w=w/w.sum(); edges.extend([(i,int(j)) for j in ns]);vals.extend(-w);edges.append((i,i));vals.append(1)
L=sparse.coo_matrix((vals,np.array(edges).T),shape=(n,n)).tocsr()
def smooth(x): x=np.clip(x,0,1);return x*x*x*(x*(6*x-15)+10)
gs=np.zeros(n);gb=np.zeros(n);gf=np.zeros(n);isbody=np.zeros(n,dtype=bool)
for g in range(n):
    ids=members[offsets[g]:offsets[g+1]];ids=ids[(ids>=47050)&(ids<49438)]-47050
    isbody[g]=np.any(members[offsets[g]:offsets[g+1]]<47050)
    if len(ids): gs[g]=shaft[ids].max();gb[g]=ball[ids].max();gf[g]=flex[ids].mean()
rad=np.linalg.norm(groupbase[:,1:]-[0,84.3],axis=1)
upper=smooth(((groupbase[:,2]-84.3)/np.maximum(rad,1e-5)+.70)/.65)
bodyfade=1-smooth((distances-5)/6)
shaftfade=1-smooth((gf-.12)/.28)
support=upper*np.where(isbody,bodyfade,shaftfade*(1-smooth((gb-.05)/.30)))
support[distances>12]=0
# Fair the positions with a bending-energy solve and smoothly varying anchors.
penalty=.002+100*(1-support)**4
A=L.T@L+sparse.diags(penalty)
factor=splu(A.tocsc())

# Position spline operator; retain its response to constants after sparsification.
K=factor.solve(np.diag(penalty))
K=support[:,None]*K+np.diag(1-support)
rows=[0];indices=[];coeff=[]
for i,row in enumerate(K):
    if support[i]<1e-5: rows.append(len(indices));continue
    ids=np.where(np.abs(row)>1e-5)[0];weights_row=row[ids].copy();weights_row[np.argmax(abs(weights_row))]+=1-weights_row.sum()
    indices.extend(ids);coeff.extend(weights_row);rows.append(len(indices))
def emit(name,values,kind):
    fmt=(lambda x:f'{float(x):.9e}f') if kind=='float' else (lambda x:str(int(x)))
    values=list(values);lines=[','.join(fmt(v) for v in values[i:i+12]) for i in range(0,len(values),12)]
    return f'static const {kind} {name}[{len(values)}]={{\n'+',\n'.join(lines)+'\n};\n'
text='// v0.7.1 constrained pelvic surface spline. Generated by tools/generate_ramp_header.py.\n#pragma once\n'
text+=emit('rampSupport',support,'float')+emit('rampRowOffsets',rows,'uint32_t')+emit('rampColumns',indices,'uint16_t')+emit('rampCoefficients',coeff,'float')
(ROOT/'src/runtime/pelvic_ramp.h').write_text(text)
print('spline entries',len(coeff),'active groups',sum(support>1e-5),'row sum error',np.max(abs(K.sum(1)-1)))
