"""Fixed topological skin ownership: 0 = shaft/body, 1 = mobile lobe."""
from ramp_mesh_data import *
from scipy import sparse
from scipy.sparse.linalg import spsolve
group=arr('graft_normals.h','graftNormalGroup',int)
n=group.max()+1
gb=np.array([ball[group==i].max() for i in range(n)])
gs=np.array([shaft[group==i].max() for i in range(n)])
faces=group[tri]
edges=np.unique(np.sort(np.vstack([faces[:,[0,1]],faces[:,[1,2]],faces[:,[2,0]]]),axis=1),axis=0)
edges=edges[edges[:,0]!=edges[:,1]]
adj=sparse.coo_matrix((np.ones(len(edges)*2),(np.r_[edges[:,0],edges[:,1]],np.r_[edges[:,1],edges[:,0]])),shape=(n,n)).tocsr()
L=sparse.diags(np.asarray(adj.sum(1)).ravel())-adj
fixed=(gb<=.03)|(gb>=.82)
for a,b in zip(offsets[:-1],offsets[1:]):
 ids=members[a:b]
 if np.any(ids<47050):fixed[group[ids[(ids>=47050)&(ids<49438)]-47050]]=True
u=np.zeros(n);u[gb>=.82]=1
free=np.flatnonzero(~fixed);boundary=np.flatnonzero(fixed)
u[free]=spsolve(L[free][:,free],-L[free][:,boundary]@u[boundary])
u=np.clip(u,0,1)
# Smooth endpoint derivatives without a hard strip of unresponsive neck.
u=u*u*(3-2*u)
values=u[group]
text='// Generated by Generate-Suspension.py; identical ownership on all welded copies.\n#pragma once\n'
text+='static const float suspensionWeight[2388]={\n'+',\n'.join(','.join(f'{v:.9e}f' for v in values[i:i+12]) for i in range(0,len(values),12))+'\n};\n'
(SRC/'suspension_weights.h').write_text(text)
print('shaft/body',int((values==0).sum()),'soft neck',int(((values>0)&(values<1)).sum()),'lobe',int((values==1).sum()))
