import re,numpy as np,json
from pathlib import Path
root=Path(__file__).resolve().parents[1];src=root/'src/runtime';s=(src/'r14_asset.h').read_text()
def arr(name):return np.array([float(v.strip().rstrip('fu')) for v in re.search(r'\b'+name+r'\[[^\]]+\]\s*=\s*\{(.*?)\};',s,re.S)[1].split(',') if v.strip()])
b=arr('r14Base').reshape(-1,3);t=arr('r14Indices').astype(int).reshape(-1,3)
selected=np.all(t<1721,axis=1)&(b[t].mean(1)[:,2]<81)&(b[t].mean(1)[:,0]<18)
edges=sorted({tuple(sorted((int(a),int(c)))) for face in t[selected] for a,c in zip(face,np.roll(face,-1))}); mids={e:len(b)+i for i,e in enumerate(edges)};out=[];parents=[]
for parent,(a,c,d) in enumerate(t):
 vs=[a,c,d]; ms=[mids.get(tuple(sorted((vs[i],vs[(i+1)%3])))) for i in range(3)];n=sum(m is not None for m in ms)
 if n==0:faces=[vs]
 elif n==3:
  x,y,z=ms;faces=[[a,x,z],[x,c,y],[z,y,d],[x,y,z]]
 elif n==1:
  k=next(i for i,m in enumerate(ms) if m is not None);v0,v1,v2=[vs[(k+i)%3] for i in range(3)];m=ms[k];faces=[[v0,m,v2],[m,v1,v2]]
 else:
  k=next(i for i,m in enumerate(ms) if m is None);v0,v1,v2=[vs[(k+i)%3] for i in range(3)];m1=ms[(k+1)%3];m2=ms[(k+2)%3];faces=[[v2,m2,m1],[v0,v1,m1],[v0,m1,m2]]
 out.extend(faces);parents.extend([parent]*len(faces))
def emit(name,a):
 a=np.asarray(a).ravel();return f'static const unsigned short {name}[{len(a)}]={{\n'+',\n'.join(','.join(str(int(x)) for x in a[i:i+18]) for i in range(0,len(a),18))+'\n};\n'
text=f'// Conforming 4:1 subdivision of scrotum and neck; generated by Generate-ScrotalDensity.py.\nstatic const UINT denseCount={len(b)+len(edges)},denseIndexCount={len(out)*3},denseEdgeCount={len(edges)};\n'+emit('denseEdges',edges)+emit('denseIndices',out)
(src/'scrotal_density_data.h').write_text(text);# Runtime keeps original vertex IDs; new shared edge midpoints are appended.
print(json.dumps({'target_triangles_before':int(sum(selected)),'target_triangles_after':int(sum(selected)*4),'total_before':len(t),'total_after':len(out),'vertices':len(b)+len(edges)}))
