from pathlib import Path
import numpy as np,re
from scipy.sparse import coo_matrix
from scipy.sparse.csgraph import dijkstra
root=Path(__file__).resolve().parents[1]
s=(root/'src/runtime/r14_asset.h').read_text()
def arr(name):
 body=re.search(r'\b'+name+r'\[[^]]+\]\s*=\s*\{(.*?)\};',s,re.S)[1]
 return np.array([float(x.strip().rstrip('fu')) for x in body.split(',') if x.strip()])
b=arr('r14Base').reshape(-1,3);f=arr('r14Indices').astype(int).reshape(-1,3)
e=np.unique(np.sort(np.concatenate([f[:,[0,1]],f[:,[1,2]],f[:,[2,0]]]),axis=1),axis=0)
d=np.linalg.norm(b[e[:,0]]-b[e[:,1]],axis=1)
g=coo_matrix((np.r_[d,d],(np.r_[e[:,0],e[:,1]],np.r_[e[:,1],e[:,0]])),shape=(len(b),len(b))).tocsr()
# The shaft-side branch of the material midline, ending before the fold.
shaft=[355,354,36,37,351,17,16,60,67,74,356]
pouch=[108,107,117,132,318,317]
ds=dijkstra(g,indices=shaft,min_only=True);dp=dijkstra(g,indices=pouch,min_only=True)
def smooth(x):
 x=np.clip(x,0,1);return x*x*x*(10+x*(-15+6*x))

from scipy.sparse import diags
from scipy.sparse.linalg import spsolve
# Dirichlet displacement interpolation: shaft crest anchors, fixed outer skin,
# a broad free attachment region. The pouch-side neck follows the attachment.
core=np.where((ds<.36)&(np.arange(len(b))<1721))[0]
free=np.where((ds>=.36)&(ds<5.5)&(b[:,2]>74.8)&(np.arange(len(b))<1721))[0]
adj=g.copy();adj.data[:]=1
L=diags(np.asarray(adj.sum(1)).ravel())-adj
W=spsolve(L[free][:,free].tocsc(),-L[free][:,core].toarray())
mask=np.zeros(len(b));mask[core]=1
lines=['// Generated by tools/Generate-RapheSupport.py.']
def emit(name,data,kind):
 vals=[f'{x:.9f}f' if kind=='float' else str(int(x)) for x in data]
 return f'static const {kind} {name}[{len(vals)}]={{\n'+',\n'.join(','.join(vals[i:i+12]) for i in range(0,len(vals),12))+'\n};\n'
lines.append(emit('rapheSupportMask',mask,'float'))
lines.append(emit('rapheSupportCore',core,'unsigned'))
lines.append(emit('rapheSupportFree',free,'unsigned'))
lines.append(emit('rapheSupportWeights',W.ravel(),'float'))
lines.append(f'static const unsigned rapheSupportCoreCount={len(core)},rapheSupportFreeCount={len(free)};')
(root/'src/runtime/raphe_support_data.h').write_text('\n'.join(lines))
print('core',len(core),'free',len(free))
