"""Measured canonical character routes; no game access or shared solver edits."""
import argparse, hashlib, importlib.util, json, re, sys
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parents[1]

def array(text,name):
    match=re.search(r"\b"+name+r"\[[^]]*\]\s*=\s*\{(.*?)\};",text,re.S)
    if not match: raise ValueError(name)
    return np.array([int(x,0) for x in re.findall(r"0x[\da-fA-F]+|\d+",match[1])],dtype=np.uint32)

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--apply',action='store_true');ap.add_argument('--base',type=Path,required=True);ap.add_argument('--out',type=Path,default=ROOT/'build/garment-lateral-hip-route');args=ap.parse_args();args.out.mkdir(parents=True,exist_ok=True)
    native=ROOT/'src/runtime/menu_retarget_body_data.h';header=ROOT/'src/runtime/jockstrap_measured_data.h';text=native.read_text();old=header.read_text();points=[];source=[];faces=[]
    for section,first in [(0,17449),(1,41435)]:
        packed=array(text,'menuRetargetBodyPacked'+str(section)).astype(np.uint8).reshape(-1,32);p=packed[:,:12].copy().view('<f4').reshape(-1,3).astype(float);offset=len(points);points.extend(p);source.extend(range(first,first+len(p)));faces.extend(array(text,'menuRetargetBodyIndices'+str(section)).reshape(-1,3)+offset)
    section=re.search(r'jockstrap_waist\[\]\s*=\s*\{(.*?)\};',old,re.S)[1];waistRecipe=[]
    for row in re.findall(r'\{\{\{(.*?)\}\}\}',section):waistRecipe.append({int(v):float(w) for v,w in re.findall(r'\{?(\d+),([\d.eE+\-]+)\}?',row) if float(w)>0})
    sys.path.insert(0,str(args.base))
    generator=args.base/'tools/garment_source_routes.py';spec=importlib.util.spec_from_file_location('source_routes',generator);shared=importlib.util.module_from_spec(spec);spec.loader.exec_module(shared);routes,proof=shared.measure_wolverine_routes(points,source,faces,waistRecipe)
    sys.path.insert(0,str(args.base))
    from malemod_base.garment_regions import reference_anatomy_semantics,anatomy_regions,anatomy_regions_header,SEMANTIC_VERSION,full_source_root_boundary,ROOT_BOUNDARY_VERSION
    semanticSource=args.base/'assets/wolverine-reference/geometry.npz';semanticGenerator=args.base/'malemod_base/garment_regions.py'
    bank=np.load(semanticSource);regionGroups=anatomy_regions(reference_anatomy_semantics(bank));regionHeader=anatomy_regions_header(regionGroups)
    opening=full_source_root_boundary(bank['derived__final_reference_positions'],bank['neck_render_data__nrIndices'].reshape(-1,3))
    (args.out/'jockstrap_regions_data.h').write_text(regionHeader,newline='\n')
    changed=old
    for name,rows in zip(['opening','strapLeft','strapRight'],[[{int(i):1.} for i in opening]]+routes):
        lines=['static const JockstrapMeasuredSample jockstrap_'+name+'[]={']
        for row in rows:
            entries=list(row.items())+[(0,0)]*(4-len(row));lines.append(' {{{'+ '},{'.join(str(k)+','+format(v,'.17g') for k,v in entries)+'}}},')
        lines.append('};');changed=re.sub(r'static const JockstrapMeasuredSample jockstrap_'+name+r'\[\]\s*=\s*\{.*?\};','\n'.join(lines),changed,flags=re.S)
    changed=changed.replace('// Measured original-edge/source-vertex donors; generated by Base tools/prepare_garment_source.py.','// Waist: Base prepare_garment_source.py; full root/hip: Base source helpers through Generate-GarmentRoute.py.')
    (args.out/'jockstrap_measured_data.h').write_text(changed,newline='\n')
    receipt=dict(schema=4,routeSteeringContractSHA256=hashlib.sha256((args.base/'malemod_base/garment_routes.py').read_bytes()).hexdigest(),rootBoundary=dict(version=ROOT_BOUNDARY_VERSION,vertices=len(opening),existingNativeIds=opening.tolist(),physicalTrianglesChanged=False),sourceCoordinates=dict(forward='+X',lateral='-Y',up='+Z',unit='measured uncalibrated native source model unit'),nativeSourceSHA256=hashlib.sha256(native.read_bytes()).hexdigest(),generatorSHA256=hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),sharedGeneratorSHA256=hashlib.sha256(generator.read_bytes()).hexdigest(),headerSHA256=hashlib.sha256(changed.encode()).hexdigest(),anatomySemantics=dict(version=SEMANTIC_VERSION,sourceAssetSHA256=hashlib.sha256(semanticSource.read_bytes()).hexdigest(),exporterSHA256=hashlib.sha256(semanticGenerator.read_bytes()).hexdigest(),regionHeaderSHA256=hashlib.sha256(regionHeader.encode()).hexdigest(),counts={k:len(v) for k,v in regionGroups.items()},fullAnatomyVertices=17528,fullAnatomyTriangles=35000),nativeDrawIndicesChanged=False,contactTopologyChanged=False,routes=proof)
    (args.out/'route-proof.json').write_text(json.dumps(receipt,indent=2)+'\n')
    if args.apply:header.write_text(changed,newline="\n");(ROOT/'src/runtime/jockstrap_regions_data.h').write_text(regionHeader,newline='\n');(ROOT/'docs/GARMENT-ROUTE.json').write_text(json.dumps(receipt,indent=2)+'\n')
    print(json.dumps(receipt,indent=2))
if __name__=='__main__':main()
