"""Generate the static geodesic junction mask (requires numpy and scipy)."""
from pathlib import Path
import re
import numpy as np
from scipy.sparse import coo_matrix
from scipy.sparse.csgraph import dijkstra
ROOT=Path(__file__).resolve().parents[1]
source=(ROOT/'src/runtime/r14_asset.h').read_text()
def array(name):
    body=re.search(r'\b'+name+r'\[[^\]]+\]\s*=\s*\{(.*?)\};',source,re.S)[1]
    return np.array([float(v.strip().rstrip('fu')) for v in body.split(',') if v.strip()])
def smooth(t):
    t=np.clip(t,0,1);return t*t*t*(10+t*(-15+6*t))
def emit(name,data,kind):
    values=[f'{v:.8f}f' if kind=='float' else str(int(v)) for v in data]
    return f'static const {kind} {name}[{len(values)}]={{\n'+',\n'.join(','.join(values[i:i+12]) for i in range(0,len(values),12))+'\n};\n'
base=array('r14Base').reshape(-1,3);tri=array('r14Indices').astype(int).reshape(-1,3)
new_start=int(re.search(r'r14NewStart=(\d+)',source)[1])
edges=np.concatenate([tri[:,[0,1]],tri[:,[1,2]],tri[:,[2,0]]]);edges=np.unique(np.sort(edges,axis=1),axis=0)
d=np.linalg.norm(base[edges[:,0]]-base[edges[:,1]],axis=1)
g=coo_matrix((np.r_[d,d],(np.r_[edges[:,0],edges[:,1]],np.r_[edges[:,1],edges[:,0]])),shape=(len(base),len(base))).tocsr()
# Fixed v0.9 vertex identities along the anterior shared seam, ending on the
# lower pouch. Geodesic distance avoids selecting the nearby rear body weld.
seeds=[36,37,351,17,16,60,67,74,356,108,107,117,132,318]
distance=dijkstra(g,indices=seeds,min_only=True)
mask=1-smooth((distance-1.5)/2.8);mask[new_start:]=0
text='// Generated by tools/Generate-UndersideBlend.py.\n'
text+=emit('undersideBlendMask',mask,'float')
ds=dijkstra(g,indices=36);de=dijkstra(g,indices=318);total=ds[318]
material=np.clip((ds-de+total)/(2*total),0,1)
text+=emit('undersideMaterial',material,'float')
text+=emit('undersideRows',g.indptr[:new_start+1],'unsigned')
text+=emit('undersideNeighbors',g.indices[:g.indptr[new_start]],'unsigned')
(ROOT/'src/runtime/underside_blend_data.h').write_text(text)
print('Active mask vertices:',np.count_nonzero(mask))
