"""Bake shared refinement frames and exact affected-face closures.

Run after changing any source mesh/binding header. --check verifies that the
checked-in product matches its source assets. No mesh coordinates are altered.
"""
from pathlib import Path
import argparse, hashlib, re

runtime=Path(__file__).resolve().parents[2]/'src/runtime'
names=['rounded_render_data.h','r14_asset.h','raphe_support_data.h','pelvic_attachment_data.h']
inputs={name:(runtime/name).read_text() for name in names}
def array(file,name):
    values=re.search(r'\b'+name+r'\[\d+\]\s*=\s*\{([^}]+)',inputs[file])[1]
    return [int(x.strip().rstrip('u')) for x in values.split(',') if x.strip()]
def triples(values):return list(zip(values[::3],values[1::3],values[2::3]))

coarse_count=int(re.search(r'r14Count=(\d+)',inputs['r14_asset.h'])[1])
parents=triples(array('rounded_render_data.h','rsFineSource'))
unique=list(dict.fromkeys(parents));lookup={tri:i for i,tri in enumerate(unique)}
fine_ids=[lookup[tri] for tri in parents]
affected=set(array('rounded_render_data.h','rsShapeIDs'))
affected.update(array('raphe_support_data.h','rapheSupportCore'))
affected.update(array('raphe_support_data.h','rapheSupportFree'))
affected.update(array('pelvic_attachment_data.h','paSeamR14'))
coarse_faces=[3*i for i,tri in enumerate(triples(array('r14_asset.h','r14Indices'))) if any(v in affected for v in tri)]
fine_faces=[3*i for i,tri in enumerate(triples(array('rounded_render_data.h','rsIndices'))) if any(v>=coarse_count for v in tri)]
digest=hashlib.sha256(''.join(inputs.values()).encode()).hexdigest()
text=f'// Generated by tools/physics/bake_geometry_bindings.py. Input SHA256 {digest}\n#pragma once\n'
text+=f'static const unsigned geometryFineFrameCount={len(unique)};\n'
def emit(name,values,kind='unsigned'):
    global text
    text+=f'static const {kind} {name}[{len(values)}]={{\n'
    text+='\n'.join(','.join(map(str,values[i:i+24]))+',' for i in range(0,len(values),24))+'\n};\n'
emit('geometryFineFrames',[v for tri in unique for v in tri],'unsigned short')
emit('geometryFineFrameIDs',fine_ids,'unsigned short')
emit('geometryRoundedFaces',coarse_faces)
emit('geometryFineFaces',fine_faces)
args=argparse.ArgumentParser();args.add_argument('--check',action='store_true');args=args.parse_args()
output=runtime/'geometry_binding_data.h'
if args.check:
    if output.read_text()!=text:raise SystemExit('Geometry bindings are stale; regenerate them.')
else:output.write_text(text)
print(f'{len(parents)} refinement vertices share {len(unique)} frames; safety faces {len(coarse_faces)} coarse, {len(fine_faces)} refined.')
