"""Refit the licensed stock Alkali tank; never reads or modifies installed files.
Supply the measured stock export generated by Export-StockTank.ps1.
"""
import argparse,hashlib,json,re,struct,sys
from pathlib import Path
import numpy as np

def array(text,name,dtype):
 match=re.search(r'\b'+name+r'\[\]\s*=\s*\{(.*?)\};',text,re.S)
 if not match:raise ValueError(name)
 return np.array([float(x) for x in re.findall(r'-?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?',match[1])],dtype=dtype)

def main():
 ap=argparse.ArgumentParser();ap.add_argument('--stock',type=Path,required=True);ap.add_argument('--base',type=Path,required=True);ap.add_argument('--output',type=Path,required=True);args=ap.parse_args()
 sys.path.insert(0,str(args.base));from malemod_base.garment_coverage import radial_coverage;from malemod_base.torso_garment_fit import refit_radially,refine_triangles,smooth_tubular_chart,clear_projected_faces
 repo=Path(__file__).resolve().parents[2];bodyPath=repo/'src/runtime/menu_retarget_body_data.h'
 source=json.loads(args.stock.read_text(encoding='utf-8-sig'));assert source['schema']=='wolverine.stock-tank/1' and source['first']==1722 and source['triangles']==1091
 text=bodyPath.read_text();packed=array(text,'menuRetargetBodyPacked0',np.uint8).reshape(-1,32)
 p=np.array([struct.unpack('<3f',bytes(v[:12])) for v in packed]);tri=array(text,'menuRetargetBodyIndices0',np.int64).reshape(-1,3)
 p1=array(text,'menuRetargetBodyPacked1',np.uint8).reshape(-1,32);n0=len(p);p=np.concatenate((p,np.array([struct.unpack('<3f',bytes(v[:12])) for v in p1])));tri=np.concatenate((tri,array(text,'menuRetargetBodyIndices1',np.int64).reshape(-1,3)+n0));sourceIDs=np.r_[np.arange(n0)+17449,np.arange(len(p1))+41435]
 # The observed upper-body resource contains neck, head and arms. Restrict the
 # measured torso patch to this tank's extent; limb intersections are omitted.
 slots0={13,14,30,31,32,33};slots1={6,7,23,24,30};membership=np.r_[np.sum(np.isin(packed[:,20:24],list(slots0))*packed[:,24:28]/255.,axis=1),np.sum(np.isin(p1[:,20:24],list(slots1))*p1[:,24:28]/255.,axis=1)];mask=np.all((p[tri][:,:,2]>89)&(p[tri][:,:,2]<146)&(membership[tri]>.7),axis=1)
 selected=tri[mask];stock=np.array([v['p'] for v in source['vertices']])
 ids={v['id']:i for i,v in enumerate(source['vertices'])};faces=np.array([ids[i] for i in source['indices']]).reshape(-1,3)
 stock,faces,lineage=refine_triangles(stock,faces)
 original=source['vertices'];generated=[];discarded=0
 for a,b in lineage:
  if a==b:generated.append(original[a]);continue
  skin={}
  for donor in (a,b):
   for bone,weight in zip(original[donor]['bone'],original[donor]['weight']):
    if weight:skin[bone]=skin.get(bone,0)+weight*.5
  selectedSkin=sorted(skin.items(),key=lambda v:(-v[1],v[0]))[:4];discarded=max(discarded,sum(skin.values())-sum(w for bone,w in selectedSkin))
  weights=np.array([w for bone,w in selectedSkin])*255/sum(w for bone,w in selectedSkin);integer=np.floor(weights).astype(int)
  for k in np.argsort(-(weights-integer))[:255-sum(integer)]:integer[k]+=1
  bones=[bone for bone,w in selectedSkin];weights=integer.tolist()
  while len(bones)<4:bones.append(bones[-1]);weights.append(0)
  uv=[]
  for k in range(2):
   value=sum(struct.unpack('<e',struct.pack('<H',original[d]['uv'][k]))[0] for d in (a,b))*.5
   uv.append(struct.unpack('<H',struct.pack('<e',value))[0])
  generated.append({'bone':bones,'weight':weights,'uv':uv,'n':np.array(original[a]['n'])*.5+np.array(original[b]['n'])*.5})
 source['vertices']=generated
 chart=smooth_tubular_chart(stock,faces)
 fitted,bindings=refit_radially(chart,p,selected,.72,fallback_distance=3.5)
 supports=np.concatenate((p[np.unique(selected)],p[selected].mean(axis=1),(p[selected[:,0]]+p[selected[:,1]])*.5,(p[selected[:,1]]+p[selected[:,2]])*.5,(p[selected[:,2]]+p[selected[:,0]])*.5))
 # UV aliases are separate draw vertices, but must share the fitted position.
 aliases={}
 for i,q in enumerate(stock):aliases.setdefault(tuple(np.round(q,5)),[]).append(i)
 aliasIDs=np.zeros(len(stock),dtype=int)
 for key,group in enumerate(aliases.values()):
  aliasIDs[group]=key;fitted[group]=fitted[group].mean(axis=0)
 fitted=clear_projected_faces(fitted,faces,supports,.72,aliases=aliasIDs)
 normal=np.zeros_like(fitted)
 for t in faces:
  n=np.cross(fitted[t[1]]-fitted[t[0]],fitted[t[2]]-fitted[t[0]])
  for i in t:normal[i]+=n
 for group in aliases.values():normal[group]=np.sum(normal[group],axis=0)
 normal/=np.maximum(np.linalg.norm(normal,axis=1)[:,None],1e-12)
 originalNormal=np.array([v['n'] for v in source['vertices']])/127.5-1
 winding=-1 if np.median(np.sum(normal*originalNormal,axis=1))<0 else 1
 normal*=winding
 # Conforming cotton uses the measured smooth body normals. Strong stock
 # wrinkles projected onto a new chest must not retain flipped shading wedges.
 bodyNormal=np.concatenate((packed[:,16:19],p1[:,16:19])).astype(float)/127.5-1
 for i,(j,weight,gap) in enumerate(bindings):
  measured=np.array(weight)@bodyNormal[selected[j]];measured/=max(np.linalg.norm(measured),1e-12)
  if np.dot(measured,normal[i])<0:normal[i]=measured
  else:normal[i]=.9*measured+.1*normal[i]
 normal/=np.maximum(np.linalg.norm(normal,axis=1)[:,None],1e-12)
 # Preserve each measured original vertex and UV alias. The normals are
 # recomputed from the fitted topology rather than stretched stock tangents.
 rows=['#pragma once','// Measured Alkali tank, refined/refitted by pinned SDK-free Base.','namespace TankTopRecipe {','static constexpr unsigned revision=5;',f'static constexpr float faceNormalSign={winding}.f;','static const NcVertex vertices[]={']
 for v,q in zip(source['vertices'],fitted):rows.append('{{'+','.join(f'{x:.9f}f' for x in q)+'},{'+','.join(map(str,v['bone']))+'},{'+','.join(map(str,v['weight']))+'}},')
 rows+=['};','static const unsigned short triangles[][3]={']+[ '{'+','.join(map(str,t))+'},' for t in faces]+['};','static const float uv[][2]={']
 rows+=['{'+','.join(f'{struct.unpack("<e",struct.pack("<H",int(x)))[0]:.9f}f' for x in v['uv'])+'},' for v in source['vertices']]+['};','static const float normals[][3]={']
 rows+=['{'+','.join(f'{x:.9f}f' for x in n)+'},' for n in normal]+['};','struct Binding {unsigned donor[3]; float weight[3];};','static const Binding bindings[]={']
 rows+=['{{'+','.join(map(str,sourceIDs[selected[j]]))+'},{'+','.join(f'{w:.9f}f' for w in weight)+'}},' for j,weight,gap in bindings]+['};','static const float donorBase[][3]={']
 donors=sorted(set(int(i) for j,w,g in bindings for i in selected[j]))
 # Compact donor base for a cheap current-body displacement update.
 rows+=['{'+','.join(f'{x:.9f}f' for x in p[i])+'},' for i in donors]+['};','static const unsigned donorIDs[]={'+','.join(map(str,sourceIDs[donors]))+'};','static const unsigned sourcePairs[][2]={']+['{'+str(original[a]['id'])+','+str(original[b]['id'])+'},' for a,b in lineage]+['};','}']
 # Covered body triangles are omitted in every native pass. This prevents
 # later bare-body passes from overwriting the forward cloth surface.
 hidden=radial_coverage(fitted,faces,p[tri].mean(axis=1),radial_axes=(0,1),height_axis=2)
 for section in range(2):
  bodyFaces=array(text,'menuRetargetBodyIndices'+str(section),np.int64).reshape(-1,3)
  mask=hidden[:len(bodyFaces)] if section==0 else hidden[-len(bodyFaces):]
  rows.insert(-1,'static const unsigned short hiddenBody'+str(section)+'[][3]={'+','.join('{'+','.join(map(str,f))+'}' for f in bodyFaces[mask])+'};')
 args.output.parent.mkdir(parents=True,exist_ok=True);args.output.write_text('\n'.join(rows)+'\n',encoding='utf-8')
 receipt={'schema':'wolverine.tank-top-binding/1','revision':5,'stockSHA256':source['packageHash'].lower(),'stockMesh':'CH_Wolverine_Alkali','stockSectionFirst':1722,'vertices':len(fitted),'triangles':len(faces),'clearance':.72,'projectedFaceClearance':.72,'maximumDisplacement':float(np.linalg.norm(fitted-stock,axis=1).max()),'subdivisionLevels':1,'sourcePairLineagePreserved':True,'uvAliasesPreserved':True,'originalSkinWeightsPreserved':True,'maximumNewVertexDiscardedWeight':discarded/255,'bodySHA256':hashlib.sha256(bodyPath.read_bytes()).hexdigest(),'headerSHA256':hashlib.sha256(args.output.read_bytes()).hexdigest(),'nativeVerified':False}
 args.output.with_suffix('.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt))
if __name__=='__main__':main()
